import type {Metadata} from 'next';
import SiteFooter from '../SiteFooter';
import SiteHeader from '../SiteHeader';
import {business} from '../config/business';

export const metadata:Metadata={title:'Pet Sitting & Dog Walking Services | Cuddle Crew Pet Care',description:'Compare owner-operated in-home Drop-In Visits, Dog Walks, Standard Overnight Care, and reviewed Continuous Care in the Sacramento area.',alternates:{canonical:'/services'},openGraph:{title:'Services | Cuddle Crew Pet Care',description:'Compare in-home pet sitting and dog walking options in the Sacramento area.',url:'/services'}};

export default function Services(){return <><SiteHeader/><main id="main-content" tabIndex={-1}><div className="shell detail-page">
 <section className="subhero detail-hero"><p className="eyebrow">Services</p><h1>Care options built around real routines.</h1><p className="lede">Cuddle Crew Pet Care provides professional in-home visits, walks, Overnight Care, and dedicated Continuous Care. Lauren reviews the household, timing, welfare, safety, scope, route, and capacity before any booking is confirmed.</p><div className="actions"><a className="button" href="/start">Start Here</a><a className="text-link" href="/rates">View detailed rates →</a></div></section>

 <section className="service-detail-grid" aria-label="Service options">
  <article id="drop-ins"><p className="eyebrow">30 · 60 · 90 minutes</p><h2>Drop-In Visits & Extended Care</h2><p>In-home care for feeding, fresh water, potty, litter or enclosure care, companionship, enrichment, routine observations, and other approved pet-care tasks that fit the booked time.</p><ul><li><strong>30 minutes</strong> for a focused routine.</li><li><strong>60 minutes</strong> when the household needs more care or unhurried interaction.</li><li><strong>90-Minute Extended Care</strong> for longer approved routines that still fit an ordinary visit.</li></ul><p>If the complete routine does not fit, Lauren may recommend more time, another service, or personalized review.</p></article>
  <article id="walks"><p className="eyebrow">On-leash dog care</p><h2>Dog Walks & Adventure Walks</h2><p>Choose a 30- or 60-minute Dog Walk, or request a 90-Minute Adventure Walk for a dog comfortable with a longer outing.</p><p>Adventure Walks require individual suitability review. Weather, air quality, surfaces, behavior, disclosed health-related considerations, and day-of safety conditions may change the outdoor portion, route, or pace. Distance and mileage are not guaranteed.</p></article>
  <article id="overnight"><p className="eyebrow">Evening through morning</p><h2>Standard Overnight Care</h2><p>Standard Overnight Care generally covers approximately {business.overnight.label}. It bundles the core overnight stay, may include reasonable departures compatible with every pet’s disclosed maximum safe and comfortable alone time and confirmed plan, and is not 24-hour continuous presence.</p><p>Daytime care is separate when needed. A 30-minute midday service, longer daytime visit, or Dog Walk can be added as a distinct service.</p><dl className="service-rate-summary"><div><dt>Dog household</dt><dd>${business.pricing.overnight.dog}</dd></div><div><dt>Cat-only household</dt><dd>${business.pricing.overnight.cat}</dd></div><div><dt>Small-animal-only household</dt><dd>Personalized review required</dd></div></dl></article>
  <article id="continuous"><p className="eyebrow">Dedicated consecutive care</p><h2>3–8 Hour Continuous Care</h2><p>Continuous Care reserves a dedicated consecutive block at the Client’s residence. Lauren generally remains for the block except for an emergency or a departure specifically discussed and approved.</p><p>The pricing is household-based and routine care is bundled. Ordinary additional-pet modifiers do not automatically apply, and the block prices are not calculated by multiplying a flat hourly rate.</p><p>Scheduled visits are usually the more affordable fit when every pet can safely and comfortably remain alone between care periods. Continuous Care is a care-fit option, not an automatic upsell.</p></article>
  <article id="continuous-24" className="wide"><p className="eyebrow">Limited availability · individualized review</p><h2>24-Hour Continuous Care</h2><p>This distinct service may be offered by request and starts at ${business.pricing.continuous24Starting} per 24-hour period. Ordinary routine care and resting time are included. It is not boarding, daycare, veterinary monitoring, or guaranteed second-by-second observation.</p><p>Availability, safety, scheduling, travel, care intensity, and approved scope require individualized review. It is not guaranteed for every household or date.</p></article>
 </section>

 <section className="decision-band"><div><p className="eyebrow">Not sure what fits?</p><h2>Plan from the routine first.</h2><p>The anonymous care planner can help compare visit frequency and duration. It does not create a booking or replace Lauren’s review.</p></div><div className="actions"><a className="button" href="/plan">Plan care</a><a className="text-link" href="/contact">Ask Lauren →</a></div></section>
 <section className="content-card detail-boundary"><h2>From service choice to confirmed care</h2><p>Service descriptions and rates help with planning. Registration, an estimate, a Meet & Greet, an invoice, or payment does not guarantee acceptance. Only an approved Precise Petcare quote and confirmed booking establish the final service, schedule, care plan, and price.</p><div className="actions"><a className="button" href="/rates">Compare rates</a><a className="button secondary" href="/start">See how to start</a></div></section>
 </div></main><SiteFooter/></>}
