import {contactFingerprint,contactKeys,escapeHtml,validateContact} from '../../lib/contact.ts';
import {clientKey,rateLimit,verifyTurnstile} from '../../lib/rate-limit.ts';
import {fetchWithTimeout,readJsonObject} from '../../lib/server-security.ts';
import {turnstileMode} from '../../lib/turnstile-config.ts';
import {smsConsentSource} from '../../config/sms.ts';
const endpoint='https://api.resend.com/emails',recipient='lauren@cuddlecrewpetcare.com',recent=new Map<string,number>();
const headers=(apiKey:string,key:string)=>({Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','User-Agent':'CuddleCrewPetCare/1.0','Idempotency-Key':key});
export async function POST(request:Request){
 if(turnstileMode(process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,process.env.TURNSTILE_SECRET_KEY)==='misconfigured'){console.error('Turnstile configuration requires both site and secret keys.');return Response.json({error:'Contact security is temporarily misconfigured. Please email Lauren directly.'},{status:503})}
 const ip=clientKey(request),limit=rateLimit(`contact:${ip}`,5,10*60_000);if(!limit.allowed)return Response.json({error:'Too many attempts. Please wait before trying again.'},{status:429,headers:{'Retry-After':String(limit.retryAfter)}});
 const apiKey=process.env.RESEND_API_KEY;if(!apiKey)return Response.json({error:'Contact delivery is not configured.'},{status:503});
 const parsed=await readJsonObject(request,8_192,contactKeys);if(!parsed.ok)return Response.json({error:parsed.error},{status:parsed.status});const checked=validateContact(parsed.value);if(!checked.ok)return Response.json({error:checked.error},{status:400});if(!await verifyTurnstile(checked.turnstileToken||'',ip))return Response.json({error:'Verification failed. Please try again.'},{status:400});if(checked.honeypot)return Response.json({ok:true});
 const data=checked.data,elapsed=Date.now()-data.startedAt;if(elapsed<3000||elapsed>7_200_000)return Response.json({error:'Please reload the form and try again.'},{status:400});
 const fingerprint=await contactFingerprint(data),now=Date.now();for(const [key,expires] of recent)if(expires<=now)recent.delete(key);if((recent.get(fingerprint)||0)>now)return Response.json({ok:true,duplicate:true});
 const smsConsentTimestamp=data.smsConsent?new Date().toISOString():undefined,smsConsentRecord=data.smsConsent?`Granted\nSMS consent source: ${smsConsentSource}\nSMS consent timestamp: ${smsConsentTimestamp}`:'Not granted';
 const text=`New website inquiry\n\nTopic: ${data.topic}\nName: ${data.name}\nEmail: ${data.replyTo}\nPhone: ${data.phone||'Not provided'}\nSMS consent: ${smsConsentRecord}\nService ZIP: ${data.zip||'Not provided'}\n\nMessage:\n${data.message}`;
 const html=`<h2>New website inquiry</h2><p><strong>Topic:</strong> ${escapeHtml(data.topic)}<br><strong>Name:</strong> ${escapeHtml(data.name)}<br><strong>Email:</strong> ${escapeHtml(data.replyTo)}<br><strong>Phone:</strong> ${escapeHtml(data.phone||'Not provided')}<br><strong>SMS consent:</strong> ${data.smsConsent?`Granted<br><strong>SMS consent source:</strong> ${smsConsentSource}<br><strong>SMS consent timestamp:</strong> ${smsConsentTimestamp}`:'Not granted'}<br><strong>Service ZIP:</strong> ${escapeHtml(data.zip||'Not provided')}</p><h3>Message</h3><p>${escapeHtml(data.message).replace(/\n/g,'<br>')}</p>`;
 try{const response=await fetchWithTimeout(endpoint,{method:'POST',headers:headers(apiKey,`contact-${fingerprint}`),body:JSON.stringify({from:'Cuddle Crew Pet Care <website@cuddlecrewpetcare.com>',to:[recipient],reply_to:data.replyTo,subject:`${data.topic} — inquiry from ${data.name}`,text,html})},8000);if(!response.ok){console.error('Resend contact delivery failed',response.status);return Response.json({error:'Unable to send inquiry.'},{status:502})}}catch{console.error('Resend contact delivery timed out or failed');return Response.json({error:'Unable to send inquiry.'},{status:503})}
 recent.set(fingerprint,now+2*60_000);
 const confirmationText=`Hi ${data.name},\n\nThanks—your ${data.topic.toLowerCase()} inquiry was sent to Lauren at Cuddle Crew Pet Care. Please allow 1–2 business days for a reply. If your requested care begins within 48 hours, submit the formal request through the client portal and call 916-252-3550.\n\nThis confirms delivery only; it is not a booking or acceptance of care.`;
 const confirmationHtml=`<div style="font-family:Arial,sans-serif;line-height:1.6;color:#3b241a"><h2>Thanks, ${escapeHtml(data.name)}.</h2><p>Your <strong>${escapeHtml(data.topic.toLowerCase())}</strong> inquiry was sent to Lauren. Please allow 1–2 business days for a reply.</p><p>If care begins within 48 hours, submit the formal request through the portal and call 916-252-3550.</p><p><strong>This confirms delivery only; it is not a booking or acceptance of care.</strong></p></div>`;
 try{const confirmation=await fetchWithTimeout(endpoint,{method:'POST',headers:headers(apiKey,`confirmation-${fingerprint}`),body:JSON.stringify({from:'Cuddle Crew Pet Care <website@cuddlecrewpetcare.com>',to:[data.replyTo],reply_to:recipient,subject:'We received your Cuddle Crew inquiry',text:confirmationText,html:confirmationHtml})},8000);if(!confirmation.ok)console.error('Resend confirmation delivery failed',confirmation.status)}catch{console.error('Resend confirmation delivery timed out or failed')}
 return Response.json({ok:true});
}
