import test from 'node:test';import assert from 'node:assert/strict';
import {applyAvailabilityOverrides,businessDate,daysBetween,holidayForDate,publicHolidays,shortNoticeKind,travelTierForMinutes,zoneForZip} from '../app/lib/business-rules.ts';
import {calculateEstimate,type EstimateInput,type EstimatePet} from '../app/lib/estimate.ts';
const pets=(...types:EstimatePet['type'][]):EstimatePet[]=>types.map(type=>({type}));
const input=(change:Partial<EstimateInput>={}):EstimateInput=>({pets:pets('dog'),service:'drop30',start:'2026-09-10',end:'2026-09-10',blocks:[0],midday:'none',zip:'95821',travelTier:'standard',now:new Date('2026-01-01T12:00:00'),...change});
const result=(change:Partial<EstimateInput>={})=>{const output=calculateEstimate(input(change));assert.deepEqual(output.issues,[]);assert(output.result);return output.result};

test('ZIP-only lookup never assigns a travel tier',()=>{assert.equal(zoneForZip('').state,'incomplete');assert.equal(zoneForZip('95821').state,'review');assert.equal(zoneForZip('99999').state,'review')});
test('ordinary one-way travel boundaries are approved and exact',()=>{assert.equal(travelTierForMinutes(10),'core');assert.equal(travelTierForMinutes(10.01),'standard');assert.equal(travelTierForMinutes(20),'standard');assert.equal(travelTierForMinutes(20.01),'extended');assert.equal(travelTierForMinutes(30.01),'farExtended');assert.equal(travelTierForMinutes(45.01),'beyond')});
test('holiday behavior stays disabled while the calendar is a placeholder',()=>{assert.deepEqual(publicHolidays(2026),[]);assert.equal(holidayForDate('2026-12-25'),undefined);assert.equal(result({start:'2026-12-25',end:'2026-12-25'}).holidayFee,0)});
test('overnight checkout is exclusive',()=>assert.deepEqual(daysBetween('2026-12-22','2026-12-26',true),['2026-12-22','2026-12-23','2026-12-24','2026-12-25']));
test('business date follows Pacific time',()=>assert.equal(businessDate(new Date('2027-01-01T06:30:00Z')),'2026-12-31'));
test('short notice separates daytime under 24h, same day, and overnight under 48h',()=>{const now=new Date('2026-08-29T11:00:00');assert.equal(shortNoticeKind('2026-08-29',15,now),'same-day');assert.equal(shortNoticeKind('2026-08-30',9,now),'short-notice');assert.equal(shortNoticeKind('2026-08-31',9,now),'standard');assert.equal(shortNoticeKind('2026-08-30',18,now,'overnight'),'short-notice')});

test('approved 30/60/90 species rates',()=>{assert.equal(result().total,30);assert.equal(result({pets:pets('cat')}).total,28);assert.equal(result({service:'drop60',pets:pets('cat')}).total,45);assert.equal(result({service:'drop90'}).total,66);assert.equal(result({service:'drop90',pets:pets('rabbit')}).total,62);assert.equal(result({service:'walk90'}).total,68)});
test('additional-pet modifiers apply without bypassing review gates',()=>{assert.equal(result({pets:pets('dog','dog')}).total,40);assert.equal(result({pets:pets('dog','cat')}).total,35);assert.equal(result({pets:pets('cat','cat','cat')}).total,38)});
test('overnight dog, cat, mixed, and small-animal-only households',()=>{assert.equal(result({service:'overnight',end:'2026-09-11'}).total,85);assert.equal(result({service:'overnight',end:'2026-09-11',pets:pets('cat')}).total,80);assert.equal(result({service:'overnight',end:'2026-09-11',pets:pets('dog','cat')}).total,90);const small=result({service:'overnight',end:'2026-09-11',pets:pets('small')});assert.equal(small.total,null);assert.equal(small.reviewRequired,true)});
test('overnight daytime options use service-specific rates',()=>{assert.equal(result({service:'overnight',end:'2026-09-11',midday:'drop30'}).total,110);assert.equal(result({service:'overnight',end:'2026-09-11',midday:'drop60'}).total,133);assert.equal(result({service:'overnight',end:'2026-09-11',midday:'drop90'}).total,151);assert.equal(result({service:'overnight',end:'2026-09-11',midday:'walk60'}).total,135)});
test('daytime travel fees and overnight travel boundary',()=>{assert.equal(result({travelTier:'extended'}).total,40);assert.equal(result({travelTier:'farExtended'}).total,50);const farNight=result({service:'overnight',end:'2026-09-11',travelTier:'extended'});assert.equal(farNight.travelFee,0);assert.equal(farNight.total,null);assert.equal(farNight.reviewRequired,true)});
test('missing travel classification and review triggers suppress final total',()=>{for(const change of [{travelTier:undefined},{pets:pets('dog','dog','dog','dog')},{pets:[{type:'dog' as const,complex:true}]}]){const value=result(change);assert.equal(value.total,null);assert.equal(value.reviewRequired,true);assert(value.serviceSubtotal>0)}});
test('short-notice fees are potential and never silently included',()=>{const value=result({start:'2026-08-30',end:'2026-08-30',now:new Date('2026-08-29T11:00:00')});assert.equal(value.potentialShortFee,10);assert.equal(value.total,null);assert.equal(value.serviceSubtotal,30)});
test('invalid estimate states are explicit',()=>{assert.deepEqual(calculateEstimate(input({start:''})).issues,['dates']);assert.deepEqual(calculateEstimate(input({zip:''})).issues,['zip']);assert.deepEqual(calculateEstimate(input({blocks:[]})).issues,['windows']);assert.deepEqual(calculateEstimate(input({service:'walk30',pets:pets('cat')})).issues,['walk-household'])});
test('availability overrides only make review status more restrictive',()=>{const overrides=[{start:'2026-12-20',end:'2026-12-28',status:'Very Limited' as const}];assert.equal(applyAvailabilityOverrides('2026-12-21','Request for Review',overrides),'Very Limited');assert.equal(applyAvailabilityOverrides('2026-12-30','Request for Review',overrides),'Request for Review')});
