import test from 'node:test';import assert from 'node:assert/strict';
import {addressFeaturesAvailable,parseAddressValidation,parseAutocomplete,routeContext} from '../app/lib/address.ts';
import {parsePlannerPrefill} from '../app/lib/planner-prefill.ts';
import {parsePlanningStateQuery,parseStoredPlanningState,planningStateQuery,sanitizePlanningState} from '../app/lib/planning-state.ts';
import {publicHolidays} from '../app/lib/business-rules.ts';

test('address validation accepts complete addresses and normalizes ZIP+4',()=>{const value=parseAddressValidation({result:{verdict:{addressComplete:true},address:{formattedAddress:'123 Main St, Sacramento, CA 95821-1234',postalAddress:{postalCode:'95821-1234',locality:'Sacramento',administrativeArea:'CA'}}}});assert.deepEqual(value,{zip:'95821',city:'Sacramento',state:'CA',normalizedDestination:'123 Main St, Sacramento, CA 95821-1234'})});
test('address validation rejects missing ZIP, incomplete verdict, and malformed data',()=>{assert.equal(parseAddressValidation({result:{verdict:{addressComplete:true},address:{postalAddress:{locality:'Sacramento'}}}}),null);assert.equal(parseAddressValidation({result:{verdict:{addressComplete:false},address:{postalAddress:{postalCode:'95821'}}}}),null);assert.equal(parseAddressValidation({nonsense:true}),null)});
test('address validation tolerates a missing locality',()=>{assert.deepEqual(parseAddressValidation({result:{verdict:{addressComplete:true},address:{postalAddress:{postalCode:'95821',administrativeArea:'CA'}}}}),{zip:'95821',city:'',state:'CA',normalizedDestination:''})});
test('autocomplete keeps valid suggestions, ignores malformed values, and limits results',()=>{const suggestions=Array.from({length:8},(_,index)=>index===1?{}:{placePrediction:{placeId:`p${index}`,text:{text:`Address ${index}`}}});const value=parseAutocomplete({suggestions});assert.equal(value.length,5);assert.equal(value[0].id,'p0');assert.equal(value.some(x=>x.id==='p1'),false);assert.deepEqual(parseAutocomplete({bad:true}),[])});
test('route context classifies only finite nonnegative routes',()=>{assert.equal(routeContext(1200,20000),'Typical service-area travel');assert.equal(routeContext(2400,50000),'Longer service-area travel');assert.equal(routeContext(3600,90000),'Unusual travel distance — contact Lauren');assert.equal(routeContext(Number.NaN,1),undefined);assert.equal(routeContext(-1,20),undefined)});
test('address feature gate requires both server values',()=>{assert.equal(addressFeaturesAvailable('key','origin'),true);assert.equal(addressFeaturesAvailable(undefined,'origin'),false);assert.equal(addressFeaturesAvailable('key',''),false)});

test('planning state sanitizes every allowed public field',()=>{const state=sanitizePlanningState({petTypes:['dog','bad','cat','small','dog','cat','dog','cat','dog','cat'],service:'drop60',blocks:[0,0,3,9,-1],midday:'30',start:'2026-09-10',end:'2026-99-99',zip:'95821',zone:'Standard',availability:'Limited Availability',address:'123 Main',behavior:'fear',medication:'pill'});assert.deepEqual(state.petTypes,['dog','cat','small','dog','cat','dog','cat','dog']);assert.equal(state.service,'drop60');assert.deepEqual(state.blocks,[0,3]);assert.equal(state.start,'2026-09-10');assert.equal(state.end,undefined);assert.equal(state.zip,'95821');assert.equal('address' in state,false)});
test('invalid planning services, dates, and ZIPs are removed',()=>{const state=sanitizePlanningState({petTypes:['nope'],service:'boarding',blocks:['0'],start:'today',end:'2026-02-30',zip:'9582'});assert.deepEqual(state.petTypes,[]);assert.equal(state.service,undefined);assert.deepEqual(state.blocks,[]);assert.equal(state.start,undefined);assert.equal(state.end,undefined);assert.equal(state.zip,undefined)});
test('planning query round trip contains only allowlisted non-sensitive fields',()=>{const query=planningStateQuery({petTypes:['dog','cat'],service:'drop30',blocks:[0,2],start:'2026-09-10',end:'2026-09-12',zip:'95821',zone:'Standard',availability:'Good Availability'});const parsed=parsePlanningStateQuery(`?${query}`);assert.deepEqual(parsed.petTypes,['dog','cat']);assert.equal(parsed.service,'drop30');assert.deepEqual(parsed.blocks,[0,2]);assert.equal(parsed.start,'2026-09-10');assert.equal(parsed.end,'2026-09-12');assert.equal(parsed.zip,'95821');for(const secret of ['address','behavior','medication','access','name','email','phone','123 Main'])assert.equal(query.toLowerCase().includes(secret.toLowerCase()),false)});
test('planning query does not invent a visit window',()=>{assert.deepEqual(parsePlanningStateQuery('?zip=95821').blocks,[]);assert.deepEqual(parsePlanningStateQuery('?windows=').blocks,[]);assert.deepEqual(parsePlanningStateQuery('?windows=0,2').blocks,[0,2]);assert.deepEqual(parsePlanningStateQuery('?windows=nope,-1,4,2').blocks,[2])});
test('malformed or invalid stored planning state becomes safe empty state',()=>{const malformed=parseStoredPlanningState('{broken');assert.deepEqual(malformed.petTypes,[]);assert.deepEqual(malformed.blocks,[]);const sanitized=parseStoredPlanningState(JSON.stringify({petTypes:['dog','invalid'],zip:'bad',address:'private'}));assert.deepEqual(sanitized.petTypes,['dog']);assert.deepEqual(sanitized.blocks,[]);assert.equal(sanitized.zip,undefined);assert.equal('address' in sanitized,false)});
test('unknown planner household never invents a composition',()=>assert.equal(parsePlannerPrefill('?planner=1&pets=4&household=Unknown'),null));
test('holiday generation remains dynamic for current and next year',()=>{const year=new Date().getFullYear();for(const value of [year,year+1]){const dates=publicHolidays(value);assert.equal(dates.length,8);assert(dates.every(item=>item.date.startsWith(`${value}-`)));assert(dates.some(item=>item.name==='Thanksgiving'))}});
