import {business} from './business';
export const providerGuide=[
 {question:'Who will actually provide the care?',why:'Consistency matters for pets, home access, and communication.',cuddle:'Lauren personally handles every accepted Cuddle Crew booking as the owner and sole sitter.',ask:'Ask whether care may be reassigned, subcontracted, or covered by a rotating team.'},
 {question:'How are requests approved?',why:'Registration should not be mistaken for a confirmed reservation.',cuddle:'Lauren manually reviews schedule, safety, health needs, temperament, and household fit before confirming service.',ask:'Ask exactly when dates become reserved and how changes are communicated.'},
 {question:'What protection is in place?',why:'Professional coverage should match work performed in clients’ homes and with entrusted pets.',cuddle:`Insured and bonded through ${business.credentials.insurer}: ${business.credentials.liabilityOccurrence.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})} general-liability occurrence coverage, care-custody-or-control coverage, and a dishonesty bond.`,ask:'Ask for current coverage types and plain-language explanations; policies and exclusions always control.'},
 {question:'What training is current?',why:'Completed credentials and training in progress should be described accurately.',cuddle:`Pet Sitters International membership is active. ${business.credentials.cpr.program} is in progress and is not yet a completed certification.`,ask:'Ask which credentials are complete, current, verifiable, or still in progress.'},
 {question:'How are safety and fit handled?',why:'A thoughtful provider sets boundaries instead of promising to accept every situation.',cuddle:'A paid Meet & Greet is required; its final rate is confirmed personally. Care is individualized, on-leash, and reviewed for heat, smoke, handling, medication, and realistic timing.',ask:'Ask about emergencies, severe weather, known bite risk, escape risk, and medication limits.'},
 {question:'How will I know what happened?',why:'Clear updates help clients make informed decisions while away.',cuddle:'Accepted bookings include portal communication, photos, and a written visit journal; GPS tracking is used when applicable.',ask:'Ask what is documented, when updates arrive, and how urgent concerns are escalated.'},
] as const;
