import type {Metadata} from 'next';
import ServiceAreaTools from '../ServiceAreaTools';
import SiteFooter from '../SiteFooter';
import SiteHeader from '../SiteHeader';
import {business} from '../config/business';

export const metadata:Metadata={title:'Service Area | Cuddle Crew Pet Care',description:'Check an address for typical Sacramento-area pet-care travel and understand the route, capacity, and booking-review boundaries.',alternates:{canonical:'/service-area'},openGraph:{title:'Service Area | Cuddle Crew Pet Care',description:'Check typical travel for owner-operated in-home pet care in the Sacramento area.',url:'/service-area'}};

export default function ServiceArea(){return <><SiteHeader/><main id="main-content" tabIndex={-1}><div className="shell detail-page">
 <section className="subhero detail-hero"><p className="eyebrow">Service area</p><h1>Sacramento-area care, reviewed address by address.</h1><p className="lede">Cuddle Crew Pet Care is based in Carmichael and serves the broader Sacramento area when the address, route, schedule, and real capacity fit. Check an address for typical daytime travel, then Lauren confirms the request personally.</p><div className="actions"><a className="button" href="#address-check">Check an address</a><a className="text-link" href="/contact">Ask about your location →</a></div></section>

 <section className="content-card area-explainer"><p className="eyebrow">How travel is reviewed</p><h2>Typical travel guides daytime pricing.</h2><div className="travel-tier-grid"><article><span>About 0–10 minutes</span><strong>{business.travel.core.name} · included</strong></article><article><span>Over 10–20 minutes</span><strong>{business.travel.standard.name} · included</strong></article><article><span>Over 20–30 minutes</span><strong>{business.travel.extended.name} · +${business.travel.extended.fee}</strong></article><article><span>Over 30–45 minutes</span><strong>{business.travel.farExtended.name} · +${business.travel.farExtended.fee}</strong></article><article><span>Beyond 45 minutes</span><strong>Personalized review required</strong></article></div><p>These tiers apply to typical one-way travel for daytime arrivals under ordinary conditions. Overnight Care outside the Standard zone and other capacity services require individualized review rather than an automatic daytime travel fee.</p></section>

 <section id="address-check" className="area-tool-section"><div className="section-heading"><div><p className="eyebrow">Private, optional lookup</p><h2>Check typical travel for your address.</h2></div><p>The address is used for the immediate server-side lookup and is not saved by Cuddle Crew Pet Care. Never enter gate, alarm, or access details here.</p></div><ServiceAreaTools/></section>

 <section className="content-card route-boundary"><h2>A location result is not a booking decision.</h2><p>Service-area eligibility and a calculable travel fee do not guarantee route feasibility, capacity, an exact arrival time, exact-date availability, or acceptance. Temporary traffic does not ordinarily redefine an established travel tier, and a ZIP alone cannot assign one.</p><div className="three-column"><div><h3>Route</h3><p>Each request must fit the actual route without compromising confirmed care.</p></div><div><h3>Capacity</h3><p>Service time, travel, documentation, buffer, and existing commitments all matter.</p></div><div><h3>Confirmation</h3><p>Only an approved Precise Petcare quote and confirmed booking establish service.</p></div></div></section>
 <section className="decision-band"><div><p className="eyebrow">The address may fit?</p><h2>Continue with the complete new-client guide.</h2></div><div className="actions"><a className="button" href="/start">Start Here</a><a className="text-link" href="/rates#estimate">Build an estimate →</a></div></section>
 </div></main><SiteFooter/></>}
