'use client';
import {useEffect,useId,useRef,useState} from 'react';
type Suggestion={id:string;label:string};
type Check={available:boolean;zip:string;city:string;travelTier?:{key:string;name:string;fee:number|null;reviewRequired:boolean};travelContext?:string};
const jsonObject=async(response:Response)=>await response.json() as Record<string,unknown>;
export default function AddressChecker({onZip}:{onZip:(zip:string)=>void}){
 const id=useId(),skipNextAutocomplete=useRef(false),checkController=useRef<AbortController|null>(null),[address,setAddress]=useState(''),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[result,setResult]=useState<Check|null>(null),[status,setStatus]=useState<'idle'|'loading'|'unavailable'|'error'>('idle'),[message,setMessage]=useState('');
 useEffect(()=>{if(skipNextAutocomplete.current){skipNextAutocomplete.current=false;return}if(address.trim().length<4){const timer=setTimeout(()=>setSuggestions([]),0);return()=>clearTimeout(timer)}const controller=new AbortController(),timer=setTimeout(async()=>{try{const response=await fetch('/api/address/suggestions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:address}),signal:controller.signal});const data=await jsonObject(response);setSuggestions(Array.isArray(data.suggestions)?data.suggestions as Suggestion[]:[]);if(data.available===false)setStatus('unavailable')}catch{if(!controller.signal.aborted){setSuggestions([]);setStatus('unavailable')}}},350);return()=>{clearTimeout(timer);controller.abort()}},[address]);
 useEffect(()=>{if(!suggestions.length)return;const dismiss=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSuggestions([]);document.getElementById(id)?.focus()}};document.addEventListener('keydown',dismiss);return()=>document.removeEventListener('keydown',dismiss)},[suggestions.length,id]);
 useEffect(()=>()=>checkController.current?.abort(),[]);
 const check=async(value=address)=>{checkController.current?.abort();const controller=new AbortController();checkController.current=controller;setStatus('loading');setMessage('');setSuggestions([]);try{const response=await fetch('/api/address/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:value}),signal:controller.signal});const data=await jsonObject(response);if(controller.signal.aborted)return;if(data.available===false){setStatus('unavailable');return}if(!response.ok){setStatus('error');setMessage(typeof data.error==='string'?data.error:'Contact Lauren for a travel review.');return}const checked=data as unknown as Check;setResult(checked);setStatus('idle');onZip(checked.zip);if(checked.travelTier)window.dispatchEvent(new CustomEvent('cuddlecrew:travel-tier',{detail:{zip:checked.zip,tier:checked.travelTier.key}}))}catch{if(!controller.signal.aborted)setStatus('unavailable')}finally{if(checkController.current===controller)checkController.current=null}};
 const selectSuggestion=(item:Suggestion)=>{skipNextAutocomplete.current=true;setSuggestions([]);setAddress(item.label);void check(item.label)};
 const editAddress=(value:string)=>{skipNextAutocomplete.current=false;setAddress(value);setSuggestions([]);setResult(null);setStatus('idle')};
 return <div className="address-checker"><p className="eyebrow">Optional address check</p><h3>Check typical travel.</h3><p>Enter an address for a private server-side estimate of ordinary one-way travel. Temporary traffic is not used to change the travel tier, and Cuddle Crew does not save the address.</p><label htmlFor={id}>Street address</label><div className="address-actions"><input id={id} value={address} autoComplete="street-address" onChange={event=>editAddress(event.target.value)} placeholder="Street address, city, CA"/><button type="button" onClick={()=>void check()} disabled={address.trim().length<6||status==='loading'}>{status==='loading'?'Checking…':'Check address'}</button></div>{suggestions.length>0&&<div className="address-suggestion-panel"><p>Suggested addresses</p><ul className="address-suggestions">{suggestions.map(item=><li key={item.id}><button type="button" onClick={()=>selectSuggestion(item)}>{item.label}</button></li>)}</ul><p className="google-attribution" translate="no">Google Maps</p></div>}{result&&<div className="address-result result" aria-live="polite"><b>{result.city?`${result.city} · `:''}{result.zip}</b><span>{result.travelTier?`${result.travelTier.name}${result.travelTier.fee===null?' · personalized review required':result.travelTier.fee?` · $${result.travelTier.fee} per daytime visit`:' · no travel fee'}`:'Personalized travel review required'}</span>{result.travelContext&&<small>{result.travelContext}</small>}<p className="google-attribution" translate="no">Google Maps</p></div>}{status==='unavailable'&&<p className="address-fallback" role="status">The address service is unavailable right now. Your address was not saved; contact Lauren for a travel review.</p>}{status==='error'&&<p className="address-fallback" role="alert">{message}</p>}<small className="privacy-note">Do not enter apartment access codes, gate codes, or other private instructions. Address details are never added to the page URL, analytics, or a saved care plan.</small></div>
}
