'use client';
import {useEffect,useId,useRef,useState} from 'react';
type Suggestion={id:string;label:string};
type Check={available:boolean;zip:string;city:string;zone:{state:string;name?:string;fee?:number};travelContext?:string};
const jsonObject=async(response:Response)=>await response.json() as Record<string,unknown>;
export default function AddressChecker({onZip}:{onZip:(zip:string)=>void}){
 const id=useId(),skipNextAutocomplete=useRef(false),[address,setAddress]=useState(''),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[result,setResult]=useState<Check|null>(null),[status,setStatus]=useState<'idle'|'loading'|'unavailable'|'error'>('idle'),[message,setMessage]=useState('');
 useEffect(()=>{if(skipNextAutocomplete.current){skipNextAutocomplete.current=false;return}if(address.trim().length<4){const timer=setTimeout(()=>setSuggestions([]),0);return()=>clearTimeout(timer)}const controller=new AbortController(),timer=setTimeout(async()=>{try{const response=await fetch('/api/address/suggestions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:address}),signal:controller.signal});const data=await jsonObject(response);setSuggestions(Array.isArray(data.suggestions)?data.suggestions as Suggestion[]:[]);if(data.available===false)setStatus('unavailable')}catch{if(!controller.signal.aborted){setSuggestions([]);setStatus('unavailable')}}},350);return()=>{clearTimeout(timer);controller.abort()}},[address]);
 useEffect(()=>{if(!suggestions.length)return;const dismiss=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSuggestions([]);document.getElementById(id)?.focus()}};document.addEventListener('keydown',dismiss);return()=>document.removeEventListener('keydown',dismiss)},[suggestions.length,id]);
 const check=async(value=address)=>{setStatus('loading');setMessage('');setSuggestions([]);try{const response=await fetch('/api/address/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:value})});const data=await jsonObject(response);if(data.available===false){setStatus('unavailable');return}if(!response.ok){setStatus('error');setMessage(typeof data.error==='string'?data.error:'Use the ZIP checker below.');return}const checked=data as unknown as Check;setResult(checked);setStatus('idle');onZip(checked.zip)}catch{setStatus('unavailable')}};
 const selectSuggestion=(item:Suggestion)=>{skipNextAutocomplete.current=true;setSuggestions([]);setAddress(item.label);void check(item.label)};
 const editAddress=(value:string)=>{skipNextAutocomplete.current=false;setAddress(value);setSuggestions([]);setResult(null);setStatus('idle')};
 return <div className="address-checker"><p className="eyebrow">Optional address check</p><h3>Find your area from your address.</h3><p>For a more precise lookup, you can enter your address here. It is sent securely to Google only to validate your location and calculate the service area. Cuddle Crew does not save it.</p><label htmlFor={id}>Street address</label><div className="address-actions"><input id={id} value={address} autoComplete="street-address" onChange={event=>editAddress(event.target.value)} placeholder="Street address, city, CA"/><button type="button" onClick={()=>void check()} disabled={address.trim().length<6||status==='loading'}>{status==='loading'?'Checking…':'Check address'}</button></div>{suggestions.length>0&&<div className="address-suggestion-panel"><p>Suggested addresses</p><ul className="address-suggestions">{suggestions.map(item=><li key={item.id}><button type="button" onClick={()=>selectSuggestion(item)}>{item.label}</button></li>)}</ul><p className="google-attribution" translate="no">Google Maps</p></div>}{result&&<div className="address-result result" aria-live="polite"><b>{result.city?`${result.city} · `:''}{result.zip}</b><span>{result.zone.state==='listed'?`${result.zone.name} zone · ${result.zone.fee?`$${result.zone.fee} per visit`:'no travel fee'}`:'Outside the listed ZIP zones — contact Lauren'}</span>{result.travelContext&&<small>{result.travelContext}</small>}<p className="google-attribution" translate="no">Google Maps</p></div>}{status==='unavailable'&&<p className="address-fallback" role="status">The address service is unavailable right now. Your address was not saved; use the ZIP checker below for the same authoritative zone and fee result.</p>}{status==='error'&&<p className="address-fallback" role="alert">{message}</p>}<small className="privacy-note">Do not enter apartment access codes, gate codes, or other private instructions. Address details are never added to the page URL, analytics, or a saved care plan.</small></div>
}
