'use client';
import Link from 'next/link';
import { useCallback, useState } from 'react';
import ServiceAreaMap from './ServiceAreaMap';
import SiteHeader from './SiteHeader';

const zones: Record<string,{name:string;fee:string}> = {};
for(const z of ['95608','95628','95821','95864']) zones[z]={name:'Core',fee:'No travel fee'};
for(const z of ['95610','95621','95662','95825','95841','95842']) zones[z]={name:'Standard',fee:'No travel fee'};
for(const z of ['95660','95661','95670','95678','95826','95827','95843','95655']) zones[z]={name:'Extended',fee:'$5 per visit'};
for(const z of ['95630','95648','95650','95677','95742','95746','95747','95762','95765']) zones[z]={name:'Far Extended',fee:'$10 per visit'};

export default function Home(){
 const [zip,setZip]=useState(''); const result=zip.length===5?zones[zip]:undefined; const selectZip=useCallback((value:string)=>setZip(value),[]);
 return <main>
  <SiteHeader/>
  <section id="top" className="hero shell"><div><p className="eyebrow">Sacramento & surrounding communities</p><h1>Care that feels like <em>your</em> kind of love.</h1><p className="lede">Thoughtful pet sitting and dog walking from someone who learns every tail wag, quiet cue, and favorite hiding spot.</p><div className="actions"><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">New client registration</a><a className="text-link" href="https://cuddlecrewpetcare.petssl.com/login">Existing client login →</a></div><div className="trust-row"><span>✓ Insured & bonded</span><span>✓ Personal, attentive care</span><span>✓ Clear pricing</span></div></div><div className="photo-stack"><div className="photo photo-main real-photo"><img src="/hero-dog.jpeg" alt="Blu, a client Australian shepherd, smiling outdoors" fetchPriority="high"/></div><span className="hero-credit">Blu · client dog</span><div className="photo photo-small"><span>Future logo</span><b>LOGO PLACEHOLDER</b></div></div></section>
  <section className="why shell"><div><p className="eyebrow">Why Cuddle Crew?</p><h2>Knowing animals is a lifelong practice.</h2></div><p>I bring lifelong experience with dogs, cats, rabbits, hamsters, fish, and small animals. I pay attention, learn each pet’s body language, and keep you connected—so they feel understood and you feel at ease.</p></section>
  <section className="solo-promise shell"><div className="solo-number">1:1</div><div><p className="eyebrow">The solo-sitter difference</p><h2>One sitter. One familiar face.</h2><p>Every Cuddle Crew booking is handled personally by Lauren. You know who is entering your home, learning your pet’s routine, and sending your updates—without a rotating team or an unfamiliar handoff.</p></div></section>
  <section className="section shell"><div className="meet-grid"><figure className="meet-photo lauren-portrait"><img src="/lauren-portrait.jpeg" alt="Lauren, owner and sole pet sitter at Cuddle Crew Pet Care" loading="lazy"/><figcaption>Lauren · owner & sole pet sitter</figcaption></figure><div><p className="eyebrow">Meet Lauren</p><h2>Personal care from someone who truly notices.</h2><p className="body-copy">Cuddle Crew Pet Care is a solo, hands-on business. I’ve spent a lifetime caring for dogs, cats, rabbits, hamsters, fish, and other small animals. I take the time to understand how each pet communicates—whether that means an enthusiastic greeting, a cautious pause, or a preference for quiet company.</p><p className="body-copy">My goal is simple: help your pets feel secure in their own home and give you genuine peace of mind while you’re away.</p><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Request availability</a></div></div></section>
  <section className="how"><div className="shell"><p className="eyebrow">How it works</p><h2>From hello to happy homecoming.</h2><div className="steps"><article><b>1</b><h3>Register</h3><p>Create your client profile and tell me about your household.</p></article><article><b>2</b><h3>Meet</h3><p>We’ll have a complimentary meet-and-greet before your first service.</p></article><article><b>3</b><h3>Confirm</h3><p>We’ll agree on care instructions, access details, and your schedule.</p></article><article><b>4</b><h3>Stay connected</h3><p>Receive photos and a thoughtful written update after visits.</p></article></div></div></section>
  <section id="services" className="section shell"><p className="eyebrow">Simple, transparent care</p><h2>Services for their real routine.</h2><div className="price-grid">
   <article><h3>Drop-in visits</h3><p>Meals, play, litter care, accepted medication routines, and thoughtful updates.</p><dl><div><dt>30 minutes</dt><dd>$30 dog · $25 cat</dd></div><div><dt>60 minutes</dt><dd>$45 dog · $40 cat</dd></div></dl></article>
   <article><h3>Dog walks</h3><p>One-on-one, on-leash walks paced for comfort, enrichment, and safe weather.</p><dl><div><dt>30 minutes</dt><dd>$30</dd></div><div><dt>60 minutes</dt><dd>$45</dd></div></dl></article>
   <article><h3>Overnight care</h3><p>In-home care approximately 6 PM–8 AM. Midday visits are separate and may be added at a discounted bundled rate.</p><dl><div><dt>One dog</dt><dd>$85</dd></div><div><dt>One cat</dt><dd>$80</dd></div></dl></article>
  </div><div className="bundle"><div><span className="eyebrow">A favorite combination</span><h3>Overnight + same-day 30-minute drop-in</h3><p>Convenient multi-visit booking for one dog.</p></div><strong>$105</strong></div><p className="fineprint">Additional dogs are $10 each. Additional cats, rabbits, birds, fish, and small animals are $5 each. Holiday daytime visits include an additional $15 per visit; holiday overnight care includes an additional $30 per day. Requests under 24 hours may add $10 per daytime visit or $25 per overnight. All requests require manual approval; multi-visit combinations are welcome.</p></section>
  <section id="care-guide" className="pet-care-guide"><div className="shell"><div className="guide-intro"><p className="eyebrow">Care by pet type</p><h2>What can a visit look like?</h2><p>Every routine is confirmed during the meet-and-greet. Open a pet type for a quick overview, then share the details that make your household unique when you register.</p></div><div className="pet-care-options">
   <details open><summary><span>Dogs</span><small>Walks, drop-ins & overnights</small></summary><p>On-leash walks, meals and fresh water, potty breaks, play or calm companionship, accepted medication routines, and visit updates. Senior dogs are welcome; dogs under one year old are considered individually. Weather and pavement conditions may change a walk to a brief potty break and indoor enrichment.</p></details>
   <details><summary><span>Cats</span><small>Drop-ins & overnights</small></summary><p>Meals and fresh water, litter care, play or quiet companionship at your cat’s pace, accepted medication routines, and updates that include appetite, litter, activity, and anything unusual. Shy cats are given space rather than forced interaction.</p></details>
   <details><summary><span>Rabbits & small animals</span><small>Routine-based drop-ins</small></summary><p>Food and water, habitat checks, basic tidying, enrichment, and observation according to your written routine. Requests are reviewed individually so timing, handling, temperature needs, and species-specific instructions are a safe fit.</p></details>
   <details><summary><span>Fish & birds</span><small>Home care check-ins</small></summary><p>Pre-portioned feeding, water or habitat observations, and basic checks following your written instructions. Specialized aquarium maintenance, veterinary procedures, and handling that requires training are not offered.</p></details>
  </div><p className="guide-note">Have a mixed-pet household or a routine not listed here? <a href="mailto:lauren@cuddlecrewpetcare.com">Ask Lauren</a>—safe, individualized requests are reviewed case by case.</p></div></section>
  <section className="included shell"><div><p className="eyebrow">Care with the details included</p><h2>More than checking a box.</h2><p>After each completed visit, you’ll receive photos and a written update covering meals and water, potty or litter details, activity, medication when applicable, and anything unusual I notice.</p></div><div className="included-list"><span>Fresh food & water</span><span>Potty breaks or litter care</span><span>Play, enrichment & affection</span><span>Medication according to written instructions</span><span>Basic home checks</span><span>Photos & a detailed visit update</span></div></section>
  <section className="before shell"><div><p className="eyebrow">Before you book</p><h2>A calm start makes for better care.</h2></div><div><p>Every new household begins with a complimentary meet-and-greet. We’ll review routines, entry and key arrangements, feeding and medication instructions, emergency contacts, and the best way to help each pet feel comfortable.</p><Link className="text-link" href="/faq">Read policies & frequently asked questions →</Link></div></section>
  <section id="area" className="area"><div className="shell"><div className="area-heading"><p className="eyebrow">Are you in the Cuddle Crew?</p><h2>Check your service area.</h2><p>Enter your home ZIP code—or select a ZIP on the map—to see your territory and any per-visit travel fee.</p></div><div className="area-tools"><ServiceAreaMap selectedZip={zip} onSelect={selectZip}/><div><div className="checker"><label htmlFor="zip">Your ZIP code</label><div><input id="zip" inputMode="numeric" maxLength={5} value={zip} onChange={e=>setZip(e.target.value.replace(/\D/g,''))} placeholder="95821"/><button onClick={()=>setZip(zip)}>Check ZIP</button></div>{zip.length===5&&<div className="result">{result?<><b>{result.name} zone</b><span>{result.fee}</span></>:<><b>Outside our listed zones</b><span>Please contact us—we may still be able to help.</span></>}</div>}</div><div className="zone-legend" aria-label="Service territory legend"><span><i style={{background:'#64FF41'}}/>Core · no fee</span><span><i style={{background:'#3075FF'}}/>Standard · no fee</span><span><i style={{background:'#FFBF5E'}}/>Extended · $5/visit</span><span><i style={{background:'#E45CFF'}}/>Far Extended · $10/visit</span></div><p className="map-note">ZIP boundaries use U.S. Census Bureau ZCTA data and are approximate service-planning areas. Final availability is confirmed after your request is reviewed.</p></div></div></div></section>
  <section className="section shell"><div className="split"><div><p className="eyebrow">Peace of mind</p><h2>Care backed by real protection.</h2><p>Insured and bonded, with clear safeguards for your home and pets. Pet CPR certification is currently in progress.</p><Link className="text-link" href="/credentials">See credentials & coverage →</Link></div><div className="review-photo real-photo"><img src="/gallery-black-dog.jpeg" alt="Calm senior black and white dog outdoors" loading="lazy"/></div></div></section>
  <section id="photos" className="gallery-section shell"><div className="gallery-heading"><div><p className="eyebrow">Life with the crew</p><h2>The pets behind the pictures.</h2></div><p>My own cats are shown separately from the client dogs I’ve cared for, so it’s always clear who’s who.</p></div>
   <div className="gallery-group own-pets"><div className="group-title"><span>My own cats</span><h3>Ponyo & Bambi</h3><p>The resident members of my personal cuddle crew.</p></div><div className="named-gallery cats-gallery"><figure><img src="/gallery-cat-closeup.jpeg" alt="Ponyo, Lauren’s gray and white cat" loading="lazy"/><figcaption>Ponyo</figcaption></figure><figure><img src="/gallery-gray-cat.jpeg" alt="Ponyo resting on the sofa" loading="lazy"/><figcaption>Ponyo</figcaption></figure><figure><img src="/bambi-portrait.jpeg" alt="Bambi, Lauren’s fluffy tabby cat" loading="lazy"/><figcaption>Bambi</figcaption></figure><figure><img src="/bambi-closeup.jpeg" alt="Close portrait of Bambi" loading="lazy"/><figcaption>Bambi</figcaption></figure><figure className="wide-pet"><img src="/cats-window.jpeg" alt="Ponyo and Bambi sitting together at the window" loading="lazy"/><figcaption>Ponyo & Bambi</figcaption></figure></div></div>
   <div className="gallery-group client-pets"><div className="group-title"><span>Client pets</span><h3>Dogs I’ve cared for</h3><p>Familiar faces from pet-sitting visits and walks.</p></div><div className="dog-stories"><article><h4>Skylar</h4><div><img src="/gallery-black-dog.jpeg" alt="Skylar sitting outside" loading="lazy"/><img src="/skylar-smile.jpeg" alt="Skylar smiling outside" loading="lazy"/><img src="/skylar-profile.jpeg" alt="Skylar relaxing on the grass" loading="lazy"/></div></article><article><h4>Loki</h4><div><img src="/gallery-tan-dog.jpeg" alt="Loki smiling on a walk" loading="lazy"/><img src="/loki-portrait.jpeg" alt="Portrait of Loki outdoors" loading="lazy"/><img src="/gallery-sunny-dog.jpeg" alt="Loki relaxing in the sunshine" loading="lazy"/></div></article><article><h4>Blu</h4><div><img src="/hero-dog.jpeg" alt="Blu smiling outdoors" loading="lazy"/><img src="/gallery-aussie.jpeg" alt="Blu smiling indoors" loading="lazy"/><img src="/blu-walk.jpeg" alt="Blu on a walk" loading="lazy"/></div></article></div></div>
   <div className="gallery-footer"><p>Client pet photos are shared with written permission. They are visual examples of pets in my care, not reviews or endorsements.</p><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Request availability</a></div></section>
  <section className="reviews shell"><p className="eyebrow">Find Cuddle Crew online</p><h2>Follow along—and share your experience.</h2><p>Visit our confirmed business pages below. Client reviews will be added here only when they are genuine and shared appropriately.</p><div className="review-links"><a href="https://share.google/O3aya8JQkApZ4prHu" target="_blank" rel="noopener noreferrer">Google Business Profile ↗</a><a href="https://www.facebook.com/profile.php?id=61593543881861" target="_blank" rel="noopener noreferrer">Facebook page ↗</a><span>Yelp · coming soon</span></div></section>
  <section className="payment-strip"><div className="shell payment-grid"><div><p className="eyebrow">Secure billing</p><h2>Pay through your client account.</h2><p>Once a booking is approved, clients receive their invoice and can pay securely through the client portal using Stripe. Cuddle Crew contributes 0.5% of Stripe-processed revenue to Stripe Climate’s carbon-removal portfolio.</p></div><a className="button" href="https://cuddlecrewpetcare.petssl.com/login">View or pay an invoice</a></div></section>
  <section className="cta"><div className="shell"><p className="eyebrow">Ready when they are</p><h2>Let’s make their next day a good one.</h2><div className="actions center"><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Register as a new client</a><a className="text-link" href="https://cuddlecrewpetcare.petssl.com/login">Existing client login →</a></div><p><a href="mailto:lauren@cuddlecrewpetcare.com">lauren@cuddlecrewpetcare.com</a> · <a href="tel:+19162523550">916-252-3550</a></p></div></section>
  <footer className="shell"><span>Cuddle Crew Pet Care · Sacramento, California</span><span><a href="https://share.google/O3aya8JQkApZ4prHu" target="_blank" rel="noopener noreferrer">Google</a> · <a href="https://www.facebook.com/profile.php?id=61593543881861" target="_blank" rel="noopener noreferrer">Facebook</a> · <Link href="/faq">Policies & FAQ</Link> · <Link href="/credentials">Credentials</Link></span></footer>
  <div className="mobile-contact"><a href="https://cuddlecrewpetcare.petssl.com/account">Register</a><a href="tel:+19162523550">Call</a><a href="mailto:lauren@cuddlecrewpetcare.com">Email</a></div>
 </main>
}
