'use client';
import Link from 'next/link';
import { useState } from 'react';

const zones: Record<string,{name:string;fee:string}> = {};
for(const z of ['95608','95628','95821','95864']) zones[z]={name:'Core',fee:'No travel fee'};
for(const z of ['95610','95621','95662','95825','95841','95842']) zones[z]={name:'Standard',fee:'No travel fee'};
for(const z of ['95660','95661','95670','95678','95826','95827','95843','95655']) zones[z]={name:'Extended',fee:'$5 per visit'};
for(const z of ['95630','95648','95650','95677','95742','95746','95747','95762','95765']) zones[z]={name:'Far Extended',fee:'$10 per visit'};

export default function Home(){
 const [zip,setZip]=useState(''); const result=zip.length===5?zones[zip]:undefined;
 return <main>
  <nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">CC</span><span>Cuddle Crew<small>Pet Care</small></span></a><div className="nav-links"><a href="#services">Services</a><a href="#area">Service area</a><Link href="/credentials">Peace of mind</Link><Link href="/faq">FAQ</Link></div><a className="button small" href="https://cuddlecrewpetcare.petssl.com/account">Register</a></nav>
  <section id="top" className="hero shell"><div><p className="eyebrow">Sacramento & surrounding communities</p><h1>Care that feels like <em>your</em> kind of love.</h1><p className="lede">Thoughtful pet sitting and dog walking from someone who learns every tail wag, quiet cue, and favorite hiding spot.</p><div className="actions"><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">New client registration</a><a className="text-link" href="https://cuddlecrewpetcare.petssl.com/login">Existing client login →</a></div><div className="trust-row"><span>✓ Insured & bonded</span><span>✓ Personal, attentive care</span><span>✓ Clear pricing</span></div></div><div className="photo-stack"><div className="photo photo-main real-photo"><img src="/lauren-cat-closeup.jpg" alt="Lauren’s blue-eyed gray tabby cat"/></div><div className="photo photo-small"><span>Future logo</span><b>LOGO PLACEHOLDER</b></div></div></section>
  <section className="why shell"><div><p className="eyebrow">Why Cuddle Crew?</p><h2>Knowing animals is a lifelong practice.</h2></div><p>I bring lifelong experience with dogs, cats, rabbits, hamsters, fish, and small animals. I pay attention, learn each pet’s body language, and keep you connected—so they feel understood and you feel at ease.</p></section>
  <section className="section shell"><div className="meet-grid"><div className="meet-photo"><img src="/lauren-kittens.jpg" alt="Two of Lauren’s kittens sitting together"/><span>Two members of my own cuddle crew</span></div><div><p className="eyebrow">Meet Lauren</p><h2>Personal care from someone who truly notices.</h2><p className="body-copy">Cuddle Crew Pet Care is a solo, hands-on business. I’ve spent a lifetime caring for dogs, cats, rabbits, hamsters, fish, and other small animals. I take the time to understand how each pet communicates—whether that means an enthusiastic greeting, a cautious pause, or a preference for quiet company.</p><p className="body-copy">My goal is simple: help your pets feel secure in their own home and give you genuine peace of mind while you’re away.</p></div></div></section>
  <section className="how"><div className="shell"><p className="eyebrow">How it works</p><h2>From hello to happy homecoming.</h2><div className="steps"><article><b>1</b><h3>Register</h3><p>Create your client profile and tell me about your household.</p></article><article><b>2</b><h3>Meet</h3><p>We’ll have a complimentary meet-and-greet before your first service.</p></article><article><b>3</b><h3>Confirm</h3><p>We’ll agree on care instructions, access details, and your schedule.</p></article><article><b>4</b><h3>Stay connected</h3><p>Receive photos and a thoughtful written update after visits.</p></article></div></div></section>
  <section id="services" className="section shell"><p className="eyebrow">Simple, transparent care</p><h2>Services for their real routine.</h2><div className="price-grid">
   <article><h3>Drop-in visits</h3><p>Meals, play, litter care, medication routines, and thoughtful updates.</p><dl><div><dt>30 minutes</dt><dd>$30 dog · $25 cat</dd></div><div><dt>60 minutes</dt><dd>$45 dog · $40 cat</dd></div></dl></article>
   <article><h3>Dog walks</h3><p>One-on-one walks paced for comfort, enrichment, and the weather.</p><dl><div><dt>30 minutes</dt><dd>$30</dd></div><div><dt>60 minutes</dt><dd>$45</dd></div></dl></article>
   <article><h3>Overnight care</h3><p>In-home care approximately 6 PM–8 AM, with a familiar evening and morning routine.</p><dl><div><dt>One dog</dt><dd>$85</dd></div><div><dt>One cat</dt><dd>$80</dd></div></dl></article>
  </div><div className="bundle"><div><span className="eyebrow">A favorite combination</span><h3>Overnight + same-day 30-minute drop-in</h3><p>Convenient multi-visit booking for one dog.</p></div><strong>$105</strong></div><p className="fineprint">Additional dogs are $10 each. Additional cats, rabbits, birds, fish, and small animals are $5 each. Multi-visit combinations are welcome.</p></section>
  <section className="included shell"><div><p className="eyebrow">Care with the details included</p><h2>More than checking a box.</h2></div><div className="included-list"><span>Fresh food & water</span><span>Potty breaks or litter care</span><span>Play, enrichment & affection</span><span>Medication according to instructions</span><span>Basic home checks</span><span>Photos & a written visit update</span></div></section>
  <section className="before shell"><div><p className="eyebrow">Before you book</p><h2>A calm start makes for better care.</h2></div><div><p>Every new household begins with a complimentary meet-and-greet. We’ll review routines, entry and key arrangements, feeding and medication instructions, emergency contacts, and the best way to help each pet feel comfortable.</p><Link className="text-link" href="/faq">Read policies & frequently asked questions →</Link></div></section>
  <section id="area" className="area"><div className="shell area-grid"><div><p className="eyebrow">Are you in the Cuddle Crew?</p><h2>Check your service area.</h2><p>Enter your home ZIP code to see your travel zone and any per-visit fee.</p></div><div className="checker"><label htmlFor="zip">Your ZIP code</label><div><input id="zip" inputMode="numeric" maxLength={5} value={zip} onChange={e=>setZip(e.target.value.replace(/\D/g,''))} placeholder="95821"/><button onClick={()=>setZip(zip)}>Check ZIP</button></div>{zip.length===5&&<div className="result">{result?<><b>{result.name} zone</b><span>{result.fee}</span></>:<><b>Outside our listed zones</b><span>Please contact us—we may still be able to help.</span></>}</div>}</div></div></section>
  <section className="section shell"><div className="split"><div><p className="eyebrow">Peace of mind</p><h2>Care backed by real protection.</h2><p>Insured and bonded, with clear safeguards for your home and pets. Pet CPR certification is currently in progress.</p><Link className="text-link" href="/credentials">See credentials & coverage →</Link></div><div className="photo review-photo"><span>Replace with happy pet photo</span><b>PHOTO PLACEHOLDER</b></div></div></section>
  <section className="reviews shell"><p className="eyebrow">Kind words, coming soon</p><h2>Reviews from the crew.</h2><p>Future reviews will appear here. These are placeholders—not customer testimonials.</p><div className="review-links"><span>Google · link placeholder</span><span>Facebook · link placeholder</span><span>Yelp · link placeholder</span></div></section>
  <section className="cta"><div className="shell"><p className="eyebrow">Ready when they are</p><h2>Let’s make their next day a good one.</h2><div className="actions center"><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Register as a new client</a><a className="text-link" href="https://cuddlecrewpetcare.petssl.com/login">Existing client login →</a></div><p><a href="mailto:lauren@cuddlecrewpetcare.com">lauren@cuddlecrewpetcare.com</a> · <a href="tel:+19162523550">916-252-3550</a></p></div></section>
  <footer className="shell"><span>Cuddle Crew Pet Care · Sacramento, California</span><span><Link href="/faq">Policies & FAQ</Link> · <Link href="/credentials">Credentials</Link></span></footer>
  <div className="mobile-contact"><a href="https://cuddlecrewpetcare.petssl.com/account">Register</a><a href="tel:+19162523550">Call</a><a href="mailto:lauren@cuddlecrewpetcare.com">Email</a></div>
 </main>
}
