'use client';
import { useCallback, useState } from 'react';
import ServiceAreaMap from './ServiceAreaMap';
import SiteHeader from './SiteHeader';
import QuoteEstimator from './QuoteEstimator';
import SocialLinks from './SocialLinks';
import AvailabilityChecker from './AvailabilityChecker';

const zones: Record<string,{name:string;fee:string}> = {};
for(const z of ['95608','95628','95821','95864']) zones[z]={name:'Core',fee:'No travel fee'};
for(const z of ['95610','95621','95662','95825','95841','95842']) zones[z]={name:'Standard',fee:'No travel fee'};
for(const z of ['95660','95661','95670','95678','95826','95827','95843','95655']) zones[z]={name:'Extended',fee:'$5 per visit'};
for(const z of ['95630','95648','95650','95677','95742','95746','95747','95762','95765']) zones[z]={name:'Far Extended',fee:'$10 per visit'};

export default function Home(){
 const [zipInput,setZipInput]=useState(''); const [checkedZip,setCheckedZip]=useState(''); const result=checkedZip.length===5?zones[checkedZip]:undefined; const selectZip=useCallback((value:string)=>{setZipInput(value);setCheckedZip(value)},[]);
 return <main>
  <SiteHeader/>
  <section id="top" className="hero shell"><div><p className="eyebrow">Sacramento & surrounding communities</p><h1>Care that feels like <em>your</em> kind of love.</h1><p className="lede">Thoughtful pet sitting and dog walking from someone who learns every tail wag, quiet cue, and favorite hiding spot.</p><div className="actions"><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">New client registration</a><a className="text-link" href="https://cuddlecrewpetcare.petssl.com/login">Existing client login →</a></div><div className="trust-row"><span>✓ Insured & bonded</span><span>✓ Personal, attentive care</span><span>✓ Clear pricing</span></div></div><div className="photo-stack"><div className="photo photo-main real-photo"><img src="/hero-dog.jpeg" alt="Blu, a client Australian shepherd, smiling outdoors" fetchPriority="high"/></div><span className="hero-credit">Blu · client dog</span><div className="photo photo-small"><span>Future logo</span><b>LOGO PLACEHOLDER</b></div></div></section>
  <section className="why shell"><div><p className="eyebrow">Why Cuddle Crew?</p><h2>Knowing animals is a lifelong practice.</h2></div><p>I bring lifelong experience with dogs, cats, rabbits, hamsters, fish, and small animals. I pay attention, learn each pet’s body language, and keep you connected—so they feel understood and you feel at ease.</p></section>
  <section className="solo-promise shell"><div className="solo-number">1:1</div><div><p className="eyebrow">The solo-sitter difference</p><h2>One sitter. One familiar face.</h2><p>Every Cuddle Crew booking is handled personally by Lauren. You know who is entering your home, learning your pet’s routine, and sending your updates—without a rotating team or an unfamiliar handoff.</p></div></section>
  <section className="section shell"><div className="meet-grid"><figure className="meet-photo lauren-portrait"><img src="/lauren-portrait.jpeg" alt="Lauren, owner and sole pet sitter at Cuddle Crew Pet Care" loading="lazy"/><figcaption>Lauren · owner & sole pet sitter</figcaption></figure><div><p className="eyebrow">Meet Lauren</p><h2>Personal care from someone who truly notices.</h2><p className="body-copy">Cuddle Crew Pet Care is a solo, hands-on business. I’ve spent a lifetime caring for dogs, cats, rabbits, hamsters, fish, and other small animals. I take the time to understand how each pet communicates—whether that means an enthusiastic greeting, a cautious pause, or a preference for quiet company.</p><p className="body-copy">My goal is simple: help your pets feel secure in their own home and give you genuine peace of mind while you’re away.</p><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Request availability</a></div></div></section>
  <section className="how"><div className="shell"><p className="eyebrow">How it works</p><h2>From hello to happy homecoming.</h2><div className="steps"><article><b>1</b><h3>Register</h3><p>Create your client profile and tell me about your household.</p></article><article><b>2</b><h3>Meet</h3><p>We’ll have a complimentary meet-and-greet before your first service.</p></article><article><b>3</b><h3>Confirm</h3><p>We’ll agree on care instructions, access details, and your schedule.</p></article><article><b>4</b><h3>Stay connected</h3><p>Receive photos and a thoughtful written update after visits.</p></article></div></div></section>
  <section id="services" className="section shell"><p className="eyebrow">Simple, transparent care</p><h2>Services for their real routine.</h2><div className="price-grid">
   <article><h3>Drop-in visits</h3><p>Meals, play, litter or habitat care, accepted medication routines, and thoughtful updates.</p><dl><div><dt>30 minutes</dt><dd>$30 dog · $25 cat</dd></div><div><dt>60 minutes</dt><dd>$45 dog · $40 cat</dd></div><div><dt>Rabbit, bird, fish tank or small animal</dt><dd>$25 · $40</dd></div></dl></article>
   <article><h3>Dog walks</h3><p>One-on-one, on-leash walks paced for comfort, enrichment, and safe weather.</p><dl><div><dt>30 minutes</dt><dd>$30</dd></div><div><dt>60 minutes</dt><dd>$45</dd></div></dl></article>
   <article><h3>Overnight care</h3><p>In-home care approximately 6 PM–8 AM. Midday visits are separate and may be added at a discounted bundled rate.</p><dl><div><dt>One dog</dt><dd>$85</dd></div><div><dt>One cat</dt><dd>$80</dd></div></dl></article>
  </div><div className="bundle"><div><span className="eyebrow">A favorite combination</span><h3>Overnight + daytime drop-in</h3><p>A $10 discounted daytime visit for one dog: add 30 minutes for $20 or 60 minutes for $35. Bundled daytime visits are scheduled within the 9 AM–6 PM eligible windows.</p></div><strong>from $105</strong></div><div className="fee-panel"><p className="eyebrow">No buried fees</p><h3>Additional charges at a glance</h3><div className="fee-grid"><article><b>Additional pets</b><span>+$10 each additional dog</span><span>+$5 each additional cat, rabbit, bird, fish tank, or small animal</span></article><article><b>Travel</b><span>Core & Standard: $0</span><span>Extended: +$5 per visit</span><span>Far Extended: +$10 per visit</span></article><article><b>Holidays</b><span>Daytime: +$15 per visit</span><span>Overnight: +$30 per day</span></article><article><b>Short notice</b><span>24–48 hours: +$10 per daytime visit</span><span>Same day: +$20 per daytime visit</span><span>Overnight under 48 hours: +$25 per day, applied manually</span></article></div><p>No sales tax is currently added to the listed pet-care service prices. Your estimate is shown before registration, and the final total is reviewed before Lauren approves the booking.</p></div></section>
  <QuoteEstimator/>
  <AvailabilityChecker/>
  <section id="care-guide" className="pet-care-guide"><div className="shell"><div className="guide-intro"><p className="eyebrow">Care by pet type</p><h2>What can a visit look like?</h2><p>Every routine is confirmed during the meet-and-greet. Open a pet type for a quick overview, then share the details that make your household unique when you register.</p></div><div className="pet-care-options">
   <details open><summary><span>Dogs</span><small>Walks, drop-ins & overnights</small></summary><p>On-leash walks, meals and fresh water, potty breaks, play or calm companionship, accepted medication routines, and visit updates. Senior dogs are welcome; dogs under one year old are considered individually. Weather and pavement conditions may change a walk to a brief potty break and indoor enrichment.</p></details>
   <details><summary><span>Cats</span><small>Drop-ins & overnights</small></summary><p>Meals and fresh water, litter care, play or quiet companionship at your cat’s pace, accepted medication routines, and updates that include appetite, litter, activity, and anything unusual. Shy cats are given space rather than forced interaction.</p></details>
   <details><summary><span>Rabbits & small animals</span><small>Drop-ins from $25</small></summary><p>Examples include rabbits, hamsters, guinea pigs, chinchillas, and similar companion animals. Routine care may include food and water, habitat checks, basic tidying, enrichment, and observation according to written instructions. Multi-habitat, specialized, unusually time-intensive, or complex routines are reviewed case by case and may require a higher care tier.</p></details>
   <details><summary><span>Fish & birds</span><small>Drop-ins from $25</small></summary><p>Bird care and typical fish-tank care may include pre-portioned feeding, water or habitat observations, and basic checks following written instructions. Fish are priced per tank rather than per individual fish. Multiple tanks, specialized aquarium maintenance, specialized handling, or complex routines require advance review and may cost more.</p></details>
  </div><p className="guide-note">Have a mixed-pet household or a routine not listed here? <a href="mailto:lauren@cuddlecrewpetcare.com">Ask Lauren</a>—safe, individualized requests are reviewed case by case.</p></div></section>
  <section className="included shell"><div><p className="eyebrow">What every visit includes</p><h2>Your rate covers a complete care experience.</h2><p>Scheduled time is only part of the service. I prepare for your pet’s routine, provide attentive in-home care, document the visit, and keep you connected through the secure client portal.</p></div><div className="included-list"><span>Fresh food & water</span><span>Potty breaks, litter, or habitat care</span><span>Play, enrichment & affection</span><span>Accepted medication routines</span><span>Basic home checks</span><span>GPS tracking when applicable</span><span>Photos & a detailed visit journal</span><span>Booking communication & follow-through</span></div></section>
  <section className="before shell"><div><p className="eyebrow">Before you book</p><h2>A calm start makes for better care.</h2></div><div><p>Every new household begins with a complimentary meet-and-greet. To make it useful, please have these details ready:</p><ul className="ready-list"><li>Feeding, medication, and daily routine notes</li><li>Your veterinarian and an emergency contact</li><li>Entry, key, alarm, and parking instructions</li><li>Behavior, triggers, hiding spots, and safety concerns</li></ul><p className="readiness-note">Registration begins the conversation; care is reserved only after I review and approve the request for schedule, safety, and fit.</p><a className="text-link" href="/faq">Read policies & frequently asked questions →</a></div></section>
  <section id="area" className="area"><div className="shell"><div className="area-heading"><p className="eyebrow">Are you in the Cuddle Crew?</p><h2>Check your service area.</h2><p>Enter your home ZIP code and select Check ZIP—or choose a ZIP directly on the map—to see your territory and any per-visit travel fee.</p></div><div className="area-tools"><ServiceAreaMap selectedZip={checkedZip} onSelect={selectZip}/><div><div className="checker"><label htmlFor="zip">Your ZIP code</label><div className="zip-actions"><input id="zip" inputMode="numeric" maxLength={5} value={zipInput} onChange={e=>setZipInput(e.target.value.replace(/\D/g,''))} onKeyDown={e=>{if(e.key==='Enter'&&zipInput.length===5)setCheckedZip(zipInput)}} placeholder="95821"/><button onClick={()=>{if(zipInput.length===5)setCheckedZip(zipInput)}}>Check ZIP</button>{(zipInput||checkedZip)&&<button className="reset-zip" onClick={()=>{setZipInput('');setCheckedZip('')}}>Reset</button>}</div>{checkedZip.length===5&&<div className="result">{result?<><b>{result.name} zone</b><span>{result.fee}</span></>:<><b>Outside our listed zones</b><span>Please contact us—we may still be able to help.</span></>}</div>}</div><div className="zone-legend" aria-label="Service territory legend"><span><i style={{background:'#64FF41'}}/>Core · no fee</span><span><i style={{background:'#3075FF'}}/>Standard · no fee</span><span><i style={{background:'#FFBF5E'}}/>Extended · $5/visit</span><span><i style={{background:'#E45CFF'}}/>Far Extended · $10/visit</span></div><p className="map-note">ZIP boundaries use U.S. Census Bureau ZCTA data and are approximate service-planning areas. Final availability is confirmed after your request is reviewed.</p></div></div></div></section>
  <section className="section shell"><div className="split"><div><p className="eyebrow">Peace of mind</p><h2>Care backed by real protection.</h2><p>Insured and bonded, with clear safeguards for your home and pets. Pet CPR certification is currently in progress.</p><a className="text-link" href="/credentials">See credentials & coverage →</a></div><div className="review-photo real-photo"><img src="/gallery-black-dog.jpeg" alt="Calm senior black and white dog outdoors" loading="lazy"/></div></div></section>
  <section id="photos" className="gallery-section shell"><div className="gallery-heading"><div><p className="eyebrow">Life with the crew</p><h2>The pets behind the pictures.</h2></div><p>My own cats are shown separately from the client dogs I’ve cared for, so it’s always clear who’s who.</p></div>
   <div className="gallery-group own-pets"><div className="group-title"><span>My own cats</span><h3>Ponyo & Bambi</h3><p>The resident members of my personal cuddle crew.</p></div><div className="named-gallery cats-gallery"><figure><img src="/gallery-cat-closeup.jpeg" alt="Ponyo, Lauren’s gray and white cat" loading="lazy"/><figcaption>Ponyo</figcaption></figure><figure><img src="/gallery-gray-cat.jpeg" alt="Ponyo resting on the sofa" loading="lazy"/><figcaption>Ponyo</figcaption></figure><figure><img src="/bambi-portrait.jpeg" alt="Bambi, Lauren’s fluffy tabby cat" loading="lazy"/><figcaption>Bambi</figcaption></figure><figure><img src="/bambi-closeup.jpeg" alt="Close portrait of Bambi" loading="lazy"/><figcaption>Bambi</figcaption></figure><figure className="wide-pet"><img src="/cats-window.jpeg" alt="Ponyo and Bambi sitting together at the window" loading="lazy"/><figcaption>Ponyo & Bambi</figcaption></figure></div></div>
   <div className="gallery-group client-pets"><div className="group-title"><span>Client pets</span><h3>Dogs I’ve cared for</h3><p>Familiar faces from pet-sitting visits and walks.</p></div><div className="dog-stories"><article><h4>Skylar</h4><div><img src="/gallery-black-dog.jpeg" alt="Skylar sitting outside" loading="lazy"/><img src="/skylar-smile.jpeg" alt="Skylar smiling outside" loading="lazy"/><img src="/skylar-profile.jpeg" alt="Skylar relaxing on the grass" loading="lazy"/></div></article><article><h4>Loki</h4><div><img src="/gallery-tan-dog.jpeg" alt="Loki smiling on a walk" loading="lazy"/><img src="/loki-portrait.jpeg" alt="Portrait of Loki outdoors" loading="lazy"/><img src="/gallery-sunny-dog.jpeg" alt="Loki relaxing in the sunshine" loading="lazy"/></div></article><article><h4>Blu</h4><div><img src="/hero-dog.jpeg" alt="Blu smiling outdoors" loading="lazy"/><img src="/gallery-aussie.jpeg" alt="Blu smiling indoors" loading="lazy"/><img src="/blu-walk.jpeg" alt="Blu on a walk" loading="lazy"/></div></article></div></div>
   <div className="gallery-footer"><p>Client pet photos are shared with written permission. They are visual examples of pets in my care, not reviews or endorsements.</p><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Request availability</a></div></section>
  <section className="reviews shell"><p className="eyebrow">Find Cuddle Crew online</p><h2>Follow along—and share your experience.</h2><p>Visit our confirmed business pages below. Client reviews will be added here only when they are genuine and shared appropriately.</p><SocialLinks /></section>
  <section className="payment-strip"><div className="shell payment-grid"><div><p className="eyebrow">Secure billing</p><h2>Pay through your client account.</h2><p>Once a booking is approved, clients receive their invoice and can pay securely through the client portal using Stripe. Cuddle Crew contributes 0.5% of Stripe-processed revenue to Stripe Climate’s carbon-removal portfolio.</p></div><a className="button" href="https://cuddlecrewpetcare.petssl.com/login">View or pay an invoice</a></div></section>
  <section id="contact" className="cta"><div className="shell"><p className="eyebrow">Questions are welcome</p><h2>Talk with a real person—not a sales funnel.</h2><p className="contact-copy">You never have to enter your phone number or email just to use the estimate planner. If you want to talk through an unusual routine, mixed-pet household, transportation need, or potential booking, contact Lauren directly.</p><div className="actions center"><a className="button" href="/contact">Contact Lauren</a><a className="text-link" href="tel:+19162523550">Call 916-252-3550 →</a><a className="text-link" href="https://cuddlecrewpetcare.petssl.com/account">Ready to register? →</a></div><p>The Contact page includes a copyable email address and optional inquiry helper. Registration is the secure next step for sharing private household and pet-care details.</p></div></section>
  <footer className="shell"><span>Cuddle Crew Pet Care · Sacramento, California</span><span className="footer-links"><SocialLinks compact /><a href="/faq">Policies & FAQ</a><a href="/credentials">Credentials</a></span></footer>
  <div className="mobile-contact"><a href="https://cuddlecrewpetcare.petssl.com/account">Register</a><a href="tel:+19162523550">Call</a><a href="/contact">Contact</a></div>
 </main>
}
