'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import {business} from './config/business';
import {zoneForZip} from './lib/business-rules';
import {calculateEstimate,PetType} from './lib/estimate';
import {parsePlannerPrefill} from './lib/planner-prefill';
type Pet={id:number;type:PetType;detail:string;complex:boolean};
const petNames:Record<PetType,string>={dog:'Dog',cat:'Cat',rabbit:'Rabbit',bird:'Bird',fish:'Fish tank',small:'Other small animal'};
const serviceLabels={drop30:'30-minute drop-in',drop60:'60-minute drop-in',walk30:'30-minute dog walk',walk60:'60-minute dog walk',overnight:'Overnight care'} as const;
const pacificNow=()=>new Date(new Date().toLocaleString('en-US',{timeZone:'America/Los_Angeles'})); const money=(n:number)=>`$${n.toFixed(0)}`;

export default function QuoteEstimator(){
 const [pets,setPets]=useState<Pet[]>([{id:1,type:'dog',detail:'',complex:false}]); const [nextId,setNextId]=useState(2),[service,setService]=useState<keyof typeof serviceLabels>('drop30'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[blocks,setBlocks]=useState<number[]>([]),[midday,setMidday]=useState<'none'|'30'|'60'>('none'),[zip,setZip]=useState(''),[copied,setCopied]=useState(false),[plannerPrefill,setPlannerPrefill]=useState(false); const overnight=service==='overnight',walk=service.startsWith('walk'),prefillApplied=useRef(false);
 const updatePet=(id:number,change:Partial<Pet>)=>setPets(list=>list.map(p=>p.id===id?{...p,...change}:p));
 const setPetCount=(count:number)=>setPets(list=>{const target=Math.max(1,Math.min(8,count));if(target<list.length)return list.slice(0,target);const additions=Array.from({length:target-list.length},(_,i)=>({id:nextId+i,type:(walk?'dog':'cat') as PetType,detail:'',complex:false}));setNextId(n=>n+additions.length);return[...list,...additions]});
 useEffect(()=>{if(prefillApplied.current)return;prefillApplied.current=true;const prefill=parsePlannerPrefill(window.location.search);if(!prefill)return;const frame=requestAnimationFrame(()=>{setPets(prefill.types.map((type,index)=>({id:index+1,type,detail:'',complex:false})));setNextId(prefill.count+1);setBlocks(prefill.blocks);setService(prefill.service);setPlannerPrefill(true);});return()=>cancelAnimationFrame(frame);},[]);
 const missing=useMemo(()=>{const items:string[]=[];if(!start||!end)items.push('Choose your service dates.');const zone=zoneForZip(zip);if(zone.state==='incomplete')items.push('Enter a complete five-digit service ZIP.');if(!overnight&&!blocks.length)items.push('Select at least one visit window.');if(walk&&pets.some(p=>p.type!=='dog'))items.push('Dog walks can only be estimated for dogs in this household.');return items;},[start,end,zip,overnight,blocks,walk,pets]);
 const result=useMemo(()=>calculateEstimate({pets,service,start,end,blocks,midday,zip,now:pacificNow()}).result,[pets,service,start,end,blocks,midday,zip]);
 const summary=result?`Cuddle Crew planning estimate: ${money(result.total)}\n${pets.map((p,i)=>`Pet ${i+1}: ${petNames[p.type]}${p.detail?` (${p.detail})`:''}`).join('\n')}\nService: ${serviceLabels[service]}\nDates: ${start} through ${end}\nFinal price, timing, and availability require Lauren's approval.`:''; const copy=async()=>{if(!summary)return;try{await navigator.clipboard.writeText(summary);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setCopied(false)}};const share=async()=>{if(!summary)return;if(!navigator.share){await copy();return;}try{await navigator.share({title:'Cuddle Crew planning estimate',text:summary});}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))await copy();}};
 return <section id="estimate" className="estimate-section"><div className="shell"><div className="estimator-heading"><p className="eyebrow">No contact details required</p><h2>Build a planning estimate around your pets.</h2><p>Tell us who needs care, choose dates and preferred windows, and the planner will include published pet, travel, holiday, and short-notice charges automatically.</p>{plannerPrefill&&<p className="planner-prefill" role="status"><strong>Planning recommendation added.</strong> Review and edit every field before relying on this estimate.</p>}</div><div className="estimator advanced-estimator"><div className="estimate-fields">
 <label>How many pets need this service?<input type="number" min="1" max="8" value={pets.length} onChange={e=>setPetCount(+e.target.value||1)}/><small>Each pet appears below so mixed-pet households are priced clearly.</small></label>
 <fieldset className="pet-roster"><legend>Your pets</legend>{pets.map((pet,index)=><div className="pet-card" key={pet.id}><b>Pet {index+1}</b><label>Pet type<select value={pet.type} onChange={e=>updatePet(pet.id,{type:e.target.value as PetType})} disabled={walk}>{walk?<option value="dog">Dog</option>:Object.entries(petNames).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{(pet.type==='small'||pet.type==='fish')&&<label>Optional detail<input value={pet.detail} maxLength={50} placeholder={pet.type==='fish'?'Example: one freshwater tank':'Example: guinea pig'} onChange={e=>updatePet(pet.id,{detail:e.target.value})}/></label>}<label className="check-field"><input type="checkbox" checked={pet.complex} onChange={e=>updatePet(pet.id,{complex:e.target.checked})}/><span>Care may be unusually detailed, time-sensitive, multi-habitat, or require specialized handling</span></label></div>)}</fieldset>
 <label>What care do you need?<select value={service} onChange={e=>{setService(e.target.value as keyof typeof serviceLabels);setMidday('none')}}>{Object.entries(serviceLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>{walk&&pets.some(p=>p.type!=='dog')&&<small>Dog walks can only be estimated for dogs. Your roster was kept unchanged; choose drop-ins or update the applicable pet types.</small>}</label>
 <div className="date-pair"><label>First service date<input type="date" value={start} onChange={e=>{setStart(e.target.value);if(end&&end<e.target.value)setEnd(e.target.value)}}/></label><label>{overnight?'Checkout date':'Last service date'}<input type="date" min={start||undefined} value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
 {!overnight&&<fieldset className="time-blocks"><legend>Preferred visit windows each day</legend><p>Select one or more. Exact arrival times are confirmed with your booking.</p>{business.windows.map((window,index)=><label key={window.id}><input type="checkbox" checked={blocks.includes(index)} onChange={()=>setBlocks(x=>x.includes(index)?x.filter(y=>y!==index):[...x,index])}/><span>{window.label}</span></label>)}{blocks.length===0&&<small>Select at least one window before a price can be calculated.</small>}</fieldset>}
 {overnight&&<fieldset className="overnight-addon"><legend>Add daytime care?</legend><p>Overnight care is approximately 6 PM–8 AM. Each same-day add-on is discounted by $10.</p>{([['none','No daytime drop-in'],['30','30 minutes · $20/day'],['60','60 minutes · $35/day']] as const).map(([value,label])=><label key={value}><input type="radio" name="midday" checked={midday===value} onChange={()=>setMidday(value)}/><span>{label}</span></label>)}</fieldset>}
 <label>Service ZIP<input inputMode="numeric" maxLength={5} value={zip} placeholder="95821" onChange={e=>setZip(e.target.value.replace(/\D/g,''))}/><small>The published travel fee is included when the ZIP is in a listed zone.</small></label><p className="timing-note"><strong>Automatic timing check:</strong> Holidays and short-notice charges are calculated from the dates and visit windows you select. Short notice is evaluated using current Pacific Time; the final charge is based on when your actual request is submitted.</p>
 </div><aside className="estimate-result" aria-live="polite">{!result?<><span>Planning estimate</span><strong>Complete the highlighted steps</strong><ul>{missing.map(item=><li key={item}>{item}</li>)}</ul><p>No price or $0 travel fee is shown until the required information has been evaluated.</p></>:<><span>Planning estimate</span><strong>{money(result.total)}</strong><small>{result.units} {overnight?'overnight day':'scheduled visit'}{result.units===1?'':'s'}</small><ul><li>Base care: {money(result.base)} per {overnight?'overnight day':'visit'}</li>{result.petFee>0&&<li>Additional pets: +{money(result.petFee)} per service</li>}<li>Travel: {result.outside?'Personal review needed':result.zone?`+${money(result.zone)} per service`:'$0'}</li>{result.addOnUnits>0&&<li>Discounted daytime add-on: {money(result.addOn)} × {result.addOnUnits}</li>}{result.holidays.length>0&&<li>Holiday care: +{money(result.holidayFee)} ({[...new Set(result.holidays.map(h=>h.name))].join(', ')})</li>}{result.shortFee>0&&<li>Short notice: +{money(result.shortFee)}{result.sameDayCount?` · ${result.sameDayCount} same-day visit${result.sameDayCount===1?'':'s'}`:''}{result.shortCount?` · ${result.shortCount} under-48-hour service${result.shortCount===1?'':'s'}`:''}</li>}{result.complex&&<li>Care-length review recommended; a 60-minute visit or custom plan may be needed</li>}</ul><p>{result.complex?'No extra complex-care charge is assumed here. Lauren will confirm whether the routine fits the selected service. ':''}No sales tax is currently added to this service-only estimate. Final pricing, timing, safety, and availability are confirmed only after Lauren reviews and approves the request.</p><div className="estimate-actions"><button type="button" className="estimate-copy" onClick={copy}>{copied?'Estimate copied':'Copy estimate summary'}</button><button type="button" className="estimate-copy" onClick={()=>window.print()}>Print estimate</button><button type="button" className="estimate-copy" onClick={share}>Share estimate</button></div><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Continue to registration</a><a className="estimate-question" href="/contact">Ask a question first →</a>{result.shortFee>0&&<p className="urgent-note">Need care within 48 hours? Submit your request through the client portal, then call <a href="tel:+19162523550">916-252-3550</a>. Short-notice care is always subject to availability.</p>}</>}</aside></div><div className="service-boundary"><strong>This planner does not create a booking.</strong><span>Fish care is priced per typical tank, not per fish. Unusually time-intensive routines may require a longer visit or custom care plan. Cuddle Crew does not provide boarding, grooming, training, continuous 24-hour care, injections, or veterinary procedures.</span></div></div></section>;
}
