'use client';
import { useMemo, useState } from 'react';

const travel: Record<string, number> = {};
for (const z of ['95608','95628','95821','95864','95610','95621','95662','95825','95841','95842']) travel[z] = 0;
for (const z of ['95660','95661','95670','95678','95826','95827','95843','95655']) travel[z] = 5;
for (const z of ['95630','95648','95650','95677','95742','95746','95747','95762','95765']) travel[z] = 10;

const serviceData = {
  dog: { drop30: ['30-minute drop-in',30,'visit'], drop60: ['60-minute drop-in',45,'visit'], walk30: ['30-minute dog walk',30,'visit'], walk60: ['60-minute dog walk',45,'visit'], overnight: ['Overnight care',85,'night'] },
  cat: { drop30: ['30-minute drop-in',25,'visit'], drop60: ['60-minute drop-in',40,'visit'], overnight: ['Overnight care',80,'night'] },
  other: { drop30: ['30-minute drop-in',20,'visit'], drop60: ['60-minute drop-in',35,'visit'] },
} as const;
const windows = ['Morning · 9 AM–12 PM','Midday · 12–3 PM','Afternoon · 3–6 PM','Evening · 6–9 PM'];
const otherTypes = ['Rabbit','Bird','Fish tank','Hamster','Guinea pig','Chinchilla','Other small animal'];
const isoToday = () => new Date().toISOString().slice(0,10);
const countDays = (a:string,b:string,overnight:boolean) => { if(!a||!b) return 1; const diff=Math.round((new Date(b+'T12:00:00').getTime()-new Date(a+'T12:00:00').getTime())/86400000); return Math.max(1,overnight?diff:diff+1); };

export default function QuoteEstimator(){
 const [pet,setPet]=useState<'dog'|'cat'|'other'>('dog'), [otherType,setOtherType]=useState('Rabbit'), [service,setService]=useState('drop30'), [start,setStart]=useState(isoToday()), [end,setEnd]=useState(isoToday()), [blocks,setBlocks]=useState([windows[0]]), [midday,setMidday]=useState<'none'|'30'|'60'>('none'), [extraDogs,setExtraDogs]=useState(0), [extraPets,setExtraPets]=useState(0), [zip,setZip]=useState(''), [holiday,setHoliday]=useState(false), [rush,setRush]=useState(false), [complex,setComplex]=useState(false);
 const options=serviceData[pet], selected=options[service as keyof typeof options] as readonly [string,number,string]|undefined, overnight=service==='overnight', days=countDays(start,end,overnight), visits=overnight?days:days*Math.max(1,blocks.length);
 const quote=useMemo(()=>{if(!selected)return null;const t=zip.length===5?travel[zip]:0,outside=zip.length===5&&t===undefined,petFee=extraDogs*10+extraPets*5,addOn=overnight?(midday==='30'?20:midday==='60'?35:0):0,holidayUnit=holiday?(overnight?30:15):0,baseUnits=overnight?days:visits,main=(selected[1]+petFee+(t??0)+holidayUnit)*baseUnits,dropUnits=overnight&&midday!=='none'?days:0,drop=(addOn+petFee+(t??0)+(holiday?15:0))*dropUnits,lastMinute=rush?(overnight?25:10*visits):0;return{total:main+drop+lastMinute,outside,t:t??0,petFee,addOn,lastMinute,dropUnits}},[selected,zip,extraDogs,extraPets,midday,holiday,rush,overnight,days,visits]);
 const switchPet=(v:'dog'|'cat'|'other')=>{setPet(v);setService('drop30');setMidday('none')};
 const toggle=(w:string)=>setBlocks(x=>x.includes(w)?x.filter(y=>y!==w):[...x,w]);
 const extraLabel=pet==='other'&&otherType==='Fish tank'?'Additional tanks or other pets':'Additional cats or small pets';
 return <section id="estimate" className="estimate-section"><div className="shell"><div className="estimator-heading"><p className="eyebrow">No contact details required</p><h2>Plan a personalized care schedule.</h2><p>Explore dates, time windows, and common add-ons privately. Nothing is sent to Cuddle Crew until you choose to register or contact Lauren.</p></div><div className="estimator advanced-estimator"><div className="estimate-fields">
 <label>What kind of pet?<select value={pet} onChange={e=>switchPet(e.target.value as 'dog'|'cat'|'other')}><option value="dog">Dog</option><option value="cat">Cat</option><option value="other">Rabbit, bird, fish or small animal</option></select></label>
 {pet==='other'&&<label>Which kind?<select value={otherType} onChange={e=>setOtherType(e.target.value)}>{otherTypes.map(x=><option key={x}>{x}</option>)}</select><small>Fish are priced per typical tank—not per fish.</small></label>}
 <label>What care do you need?<select value={service} onChange={e=>{setService(e.target.value);setMidday('none')}}>{Object.entries(options).map(([id,x])=><option key={id} value={id}>{x[0]}</option>)}</select></label>
 <div className="date-pair"><label>First service date<input type="date" min={isoToday()} value={start} onInput={e=>{const value=e.currentTarget.value;setStart(value);if(end < value)setEnd(value)}}/></label><label>{overnight?'Checkout date':'Last service date'}<input type="date" min={start} value={end} onInput={e=>setEnd(e.currentTarget.value)}/></label></div>
 {!overnight&&<fieldset className="time-blocks"><legend>Preferred visit windows each day</legend><p>Select one or more. Exact arrival times are confirmed with your booking.</p>{windows.map(w=><label key={w}><input type="checkbox" checked={blocks.includes(w)} onChange={()=>toggle(w)}/><span>{w}</span></label>)}{blocks.length===0&&<small>Please select at least one window; the estimate uses one visit per day until you do.</small>}</fieldset>}
 {overnight&&<fieldset className="overnight-addon"><legend>Add a daytime drop-in?</legend><p>Overnight care is approximately 6 PM–8 AM. Daytime care is separate, with each add-on drop-in discounted by $10.</p><label><input type="radio" name="midday" checked={midday==='none'} onChange={()=>setMidday('none')}/><span>No daytime drop-in</span></label><label><input type="radio" name="midday" checked={midday==='30'} onChange={()=>setMidday('30')}/><span>30 minutes · $20/day</span></label><label><input type="radio" name="midday" checked={midday==='60'} onChange={()=>setMidday('60')}/><span>60 minutes · $35/day</span></label></fieldset>}
 <label>Additional dogs<input type="number" min="0" max="10" value={extraDogs} onChange={e=>setExtraDogs(Math.max(0,Math.min(10,+e.target.value||0)))}/><small>+$10 each, for each scheduled service</small></label><label>{extraLabel}<input type="number" min="0" max="10" value={extraPets} onChange={e=>setExtraPets(Math.max(0,Math.min(10,+e.target.value||0)))}/><small>+$5 each, for each scheduled service</small></label><label>Service ZIP<input inputMode="numeric" maxLength={5} value={zip} placeholder="95821" onChange={e=>setZip(e.target.value.replace(/\D/g,''))}/><small>Includes the published travel fee when applicable.</small></label><label className="check-field"><input type="checkbox" checked={holiday} onChange={e=>setHoliday(e.target.checked)}/><span>These services fall on a listed holiday</span></label><label className="check-field"><input type="checkbox" checked={rush} onChange={e=>setRush(e.target.checked)}/><span>Request is under 24 hours away</span></label><label className="check-field"><input type="checkbox" checked={complex} onChange={e=>setComplex(e.target.checked)}/><span>This routine involves multiple habitats, unusually detailed preparation, specialized handling, or time-sensitive care</span></label>
 </div>{quote&&<aside className="estimate-result" aria-live="polite"><span>Planning estimate</span><strong>${quote.total}</strong><small>{overnight?`${days} overnight${days===1?'':'s'}`:`${visits} visit${visits===1?'':'s'} across ${days} day${days===1?'':'s'}`}</small><ul><li>Base care: ${selected![1]} per {selected![2]}</li>{pet==='other'&&<li>Primary care: {otherType}{otherType==='Fish tank'?' (one typical tank)':''}</li>}{quote.dropUnits>0&&<li>Discounted daytime add-on: ${quote.addOn} × {quote.dropUnits}</li>}{quote.petFee>0&&<li>Additional pets: +${quote.petFee} per service</li>}<li>Travel: {quote.outside?'Personal review needed':quote.t?`+$${quote.t} per service`:'$0'}</li>{holiday&&<li>Holiday pricing included</li>}{quote.lastMinute>0&&<li>Last-minute charge: +${quote.lastMinute}{overnight?' once':' total'}</li>}{complex&&<li>Complex-care review needed; an adjusted care tier may apply</li>}</ul><p>{complex?'This total does not include a possible complex-care adjustment. ':''}Final pricing, timing, and availability are confirmed only after Lauren manually reviews and approves the request.</p><a className="button" href="https://cuddlecrewpetcare.petssl.com/account">Continue to registration</a><a className="estimate-question" href="/contact">Ask a question first →</a></aside>}</div><div className="service-boundary"><strong>This planner does not create a booking.</strong><span>Routine small-animal drop-ins start at $20 for 30 minutes or $35 for 60 minutes. Multi-habitat, specialized, unusually time-intensive, or complex routines are reviewed case by case and may require a higher care tier. No boarding, grooming, training, continuous 24-hour care, or veterinary procedures are provided.</span></div></div></section>;
}
