import type {Metadata} from 'next';
/* eslint-disable @next/next/no-html-link-for-pages */
import SiteHeader from '../SiteHeader';
import SocialLinks from '../SocialLinks';
import {business} from '../config/business';

export const metadata:Metadata={title:'Start Here | Cuddle Crew Pet Care',description:'Choose a clear next step for personalized Sacramento pet care: service area, care planning, pricing, availability, or a conversation with Lauren.',alternates:{canonical:'/start'},openGraph:{title:'Start Here | Cuddle Crew Pet Care',description:'Choose a clear next step for personalized Sacramento pet care.',url:'/start'}};
const pathways=[
 {step:'1',title:'Check service area',body:'Confirm whether your ZIP is in a listed zone and see any published travel fee.',href:'/#area',label:'Check service area'},
 {step:'2',title:'Plan care',body:'Use a short, anonymous guide to find a sensible visit-length and schedule starting point.',href:'/plan',label:'Plan care'},
 {step:'3',title:'Estimate pricing',body:'Build a no-obligation estimate with your pet types, preferred windows, dates, and ZIP.',href:'/#estimate',label:'Estimate pricing'},
 {step:'4',title:'Check preliminary availability',body:'After selecting dates in the estimate, see a broad planning indicator. It never reserves care.',href:'/#estimate',label:'Check preliminary availability'},
 {step:'5',title:'Talk with Lauren',body:'Ask a question, discuss a special routine, or get help choosing the right next step.',href:'/contact',label:'Contact Lauren'},
] as const;
export default function Start(){return <><SiteHeader/><main><div className="shell start-page"><section className="subhero start-hero"><p className="eyebrow">A simple place to begin</p><h1>Find your next pet-care step.</h1><p className="lede">Start with your service area, then plan care and estimate pricing when it is useful. Lauren reviews every household, request, and final schedule personally.</p><a className="button" href="/#area">Start with service area</a><p className="start-helper">Already a client? <a href={business.portal.login}>Open your client portal</a>.</p></section><nav className="start-pathways" aria-label="Choose your next step"><ol>{pathways.map(path=><li key={path.title}><span aria-hidden="true">{path.step}</span><div><h2>{path.title}</h2><p>{path.body}</p><a className={path.step==='1'?'button small':'text-link'} href={path.href}>{path.label}{path.step==='1'?'':' →'}</a></div></li>)}</ol></nav><section className="content-card start-next"><p className="eyebrow">What happens next?</p><h2>Planning first, personal review before booking.</h2><ol className="start-steps"><li>Explore the tools without entering contact, access, or medical details.</li><li>Register through the secure client portal when you are ready.</li><li>Lauren schedules a complimentary meet-and-greet, then reviews the request before confirming care.</li></ol><p className="fine-print">Online tools provide planning guidance only. Availability, timing, fit, and final pricing require Lauren&apos;s review; no online step creates a reservation.</p></section><section className="cta start-cta"><p className="eyebrow">Ready to continue?</p><h2>Start a secure new-client request.</h2><p>Use the portal for private household, pet-profile, and request details. Prefer a conversation first? <a href="/contact">Contact Lauren</a>.</p><a className="button" href={business.portal.register}>New client registration</a><SocialLinks compact/></section></div></main></>}
