import SiteHeader from '../SiteHeader';

export default function Credentials(){return <main className="shell">
 <SiteHeader/>
 <section className="subhero"><p className="eyebrow">Credentials & peace of mind</p><h1>Protected care, clearly explained.</h1><p className="lede">Your pets, home, and trust matter. Cuddle Crew Pet Care is insured and bonded for professional in-home care.</p></section>
 <section className="content-card membership-card"><div><p className="eyebrow">Professional membership</p><h2>Pet Sitters International member</h2><p>Lauren Blalock and Cuddle Crew Pet Care are members in good standing with Pet Sitters International and have agreed to follow PSI’s Code of Conduct and Quality Standards.</p><p><strong>Current membership expires August 19, 2027.</strong></p><p className="fine-print">PSI membership is a professional membership and is separate from Pet CPR certification.</p></div><a className="certificate-link" href="/psi-membership-certificate.jpg" target="_blank" rel="noopener noreferrer"><img src="/psi-membership-certificate.jpg" alt="Pet Sitters International certificate of membership for Lauren Blalock and Cuddle Crew Pet Care, expiring August 19, 2027"/><span>View membership certificate ↗</span></a></section>
 <section className="content-card"><p className="eyebrow">Insurance & bonding</p><h2>What the coverage means</h2><p>Coverage is arranged through <a href="https://www.business-insurers.com/pet-sitter-dog-walker-pet-taxi-and-pooper-scooper-insurance/" target="_blank" rel="noopener noreferrer"><strong>Business Insurers of the Carolinas</strong></a>, an independent agency specializing in insurance for pet-care professionals.</p><div className="coverage-list"><details open><summary><span>General liability</span><strong>$1M occurrence / $2M aggregate</strong></summary><p>Designed to respond to covered third-party bodily-injury or property-damage claims arising from negligence and may help with covered legal costs, subject to the policy’s terms, exclusions, and limits.</p></details><details><summary><span>Care, custody, or control</span><strong>$50,000 per claim / $50,000 annual</strong></summary><p>Pet-specific protection for covered client pets and client property while in the sitter’s care, custody, or control. Business Insurers explains that this coverage can include veterinary medical expenses and accidental pet injuries, subject to the policy’s terms, exclusions, and limits.</p></details><details><summary><span>Dishonesty bond</span><strong>$5,000</strong></summary><p>Designed to protect against covered dishonest acts, such as theft of a client’s property or money, subject to the bond’s terms, exclusions, and limits.</p></details></div><p className="fine-print">These are plain-language summaries, not a guarantee that a particular event will be covered. The issued insurance policy and bond control. <a href="https://www.business-insurers.com/faqs/" target="_blank" rel="noopener noreferrer">Read the insurer’s coverage FAQ ↗</a></p></section>
 <section className="content-card"><p className="eyebrow">Training status</p><h2>Pet Tech® PetSaver™ certification in progress</h2><p><strong>This certification is not yet completed.</strong> Lauren is working toward Pet Tech’s eight-hour PetSaver™ Pet CPR, First Aid & Care certification. The program covers CPR techniques, first aid, health and wellness, plus dental and senior pet care for dogs and cats—the additional topics that distinguish the eight-hour program from the shorter class.</p><p><a className="text-link" href="https://pettech.net/cpr-day/" target="_blank" rel="noopener noreferrer">Learn about Pet Tech’s eight-hour PetSaver training ↗</a></p></section>
 <section className="content-card"><h2>What attentive care means</h2><p>Every visit is shaped around your instructions and your pet’s body language, comfort, energy, and routine. You receive thoughtful updates so you can feel connected while away.</p></section>
 <p><a className="text-link" href="/">← Return home</a> · <a className="text-link" href="/faq">Read policies & FAQ →</a></p>
 </main>}
