import RatesEstimator from '../RatesEstimator';
import SiteFooter from '../SiteFooter';
import SiteHeader from '../SiteHeader';
import {business} from '../config/business';

import {publicPageMetadata} from '../lib/metadata';
export const metadata=publicPageMetadata({title:"Pet Care Rates & Estimate | Cuddle Crew Pet Care",description:"Review approved public pet-sitting, dog-walking, Overnight, and Continuous Care rates, then build a preliminary estimate.",path:'/rates'});

export default function Rates(){return <><SiteHeader/><main id="main-content" tabIndex={-1}><div className="shell detail-page">
 <section className="subhero detail-hero"><p className="eyebrow">Rates</p><h1>Clear prices for standard care.</h1><p className="lede">These approved public rates are planning anchors. Final service, modifiers, availability, scope, and pricing require Lauren’s review and an approved Precise Petcare quote.</p><div className="actions"><a className="button" href="#estimate">Build an estimate</a><a className="text-link" href="/services">Compare services →</a></div></section>

 <section className="rate-section" aria-labelledby="daytime-rates"><div className="rate-heading"><p className="eyebrow">Visits & walks</p><h2 id="daytime-rates">Daytime care</h2></div><div className="rate-table-grid">
  <article><h3>Drop-In Visits</h3><dl className="rate-list"><div><dt>30 minutes</dt><dd>Dog ${business.pricing.drop30.dog}<br/>Cat/small animal ${business.pricing.drop30.cat}</dd></div><div><dt>60 minutes</dt><dd>Dog ${business.pricing.drop60.dog}<br/>Cat/small animal ${business.pricing.drop60.cat}</dd></div><div><dt>90-Minute Extended Care</dt><dd>Dog ${business.pricing.drop90.dog}<br/>Cat/small animal ${business.pricing.drop90.cat}</dd></div></dl></article>
  <article><h3>Dog Walks</h3><dl className="rate-list"><div><dt>30 minutes</dt><dd>${business.pricing.walk30}</dd></div><div><dt>60 minutes</dt><dd>${business.pricing.walk60}</dd></div><div><dt>90-Minute Adventure Walk</dt><dd>${business.pricing.walk90}</dd></div></dl><p className="fine-print">Adventure Walks require individual suitability and day-of safety review.</p></article>
 </div></section>

 <section className="rate-section rate-section-tint" aria-labelledby="overnight-rates"><div className="rate-heading"><p className="eyebrow">Overnight</p><h2 id="overnight-rates">Standard Overnight Care</h2><p>Approximately {business.overnight.label}; not 24-hour continuous presence. Separate daytime care can be added when needed.</p></div><div className="rate-table-grid">
  <article><h3>Household rate</h3><dl className="rate-list emphasized"><div><dt>Dog household</dt><dd>${business.pricing.overnight.dog}</dd></div><div><dt>Cat-only household</dt><dd>${business.pricing.overnight.cat}</dd></div><div><dt>Small-animal-only household</dt><dd>Personalized review required</dd></div></dl></article>
  <article><h3>Separate 30-minute midday care</h3><dl className="rate-list"><div><dt>Dog household</dt><dd>${business.pricing.overnightMidday30.dog}</dd></div><div><dt>Cat/small-animal household</dt><dd>${business.pricing.overnightMidday30.cat}</dd></div></dl><p>Longer midday care uses the applicable 60- or 90-minute daytime rate. A midday Dog Walk uses the applicable Dog Walk rate.</p></article>
 </div></section>

 <section className="rate-section" aria-labelledby="continuous-rates"><div className="rate-heading"><p className="eyebrow">Dedicated household blocks</p><h2 id="continuous-rates">Continuous Care</h2><p>Fixed block pricing includes ordinary routine care for the household. Normal per-pet modifiers do not apply automatically.</p></div><div className="continuous-ladder">{Object.entries(business.pricing.continuous).map(([hours,price])=><div key={hours}><span>{hours==='8'?'8-hour Extended Day':`${hours} hours`}</span><strong>${price}</strong></div>)}</div><div className="continuous-24-callout"><div><p className="eyebrow">Limited 24-Hour Continuous Care</p><h3>Starts at ${business.pricing.continuous24Starting} per 24-hour period</h3><p>Limited capacity, request, individualized scope and scheduling review, and a final quote are required. The starting amount is bundled, not $30 multiplied by 24.</p></div><a className="text-link" href="/services#continuous-24">Read the service distinction →</a></div></section>

 <section className="rate-section modifiers" aria-labelledby="modifier-rates"><div className="rate-heading"><p className="eyebrow">Possible additions</p><h2 id="modifier-rates">Modifiers and review boundaries</h2></div><div className="modifier-grid">
  <article><h3>Additional pets</h3><p>When the complete routine safely fits the booked ordinary service: +${business.pricing.additionalDog} per additional dog and +${business.pricing.additionalCat} per additional cat or small animal where appropriate.</p><p>Continuous Care remains household-based, with no automatic ordinary per-pet modifier.</p></article>
  <article><h3>Typical daytime travel</h3><p>Up to 20 minutes one way is included. Over 20–30 minutes may add ${business.travel.extended.fee} per daytime arrival; over 30–45 minutes may add ${business.travel.farExtended.fee}. Beyond 45 minutes requires personalized review and is generally unavailable unless approved.</p><a className="text-link" href="/service-area">Check your address →</a></article>
  <article><h3>Holiday & peak dates</h3><p>Qualifying daytime visits and 3–8 hour Continuous Care add ${business.pricing.holidayVisit} per arrival or block. Qualifying Overnights and 24-Hour periods add ${business.pricing.holidayOvernight} per night or period.</p><a className="text-link" href="/holidays">See approved dates →</a></article>
  <article><h3>Short notice</h3><p>A daytime request under 24 hours may add ${business.pricing.shortNoticeVisit}; a same-day request may instead add ${business.pricing.sameDayVisit}. An Overnight request under 48 hours may add ${business.pricing.shortNoticeOvernight} per night. These discretionary charges never guarantee availability.</p></article>
 </div><p className="rate-boundary">No automatic puppy, senior, anxious-pet, medical, or disability surcharge applies. A higher price never makes unsafe, unlawful, uninsured, or out-of-scope care acceptable. Nonstandard care may require a longer service, custom scope, referral, or personalized review.</p></section>
 </div><RatesEstimator/><section className="cta rates-cta"><div className="shell"><p className="eyebrow">Estimate complete?</p><h2>Use the new-client path before requesting care.</h2><p>The estimator does not reserve dates or create a quote. Lauren confirms the right service, route, schedule, care plan, and capacity.</p><div className="actions center"><a className="button" href="/start">Start Here</a><a className="text-link" href="/contact">Ask a pricing question →</a></div></div></section></main><SiteFooter/></>}
