'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {business} from '../config/business';
import {assessCarePlan,type BehaviorNeed,type LifeStage,type MedicationNeed,type RoutineComplexity,type SeparationNeed,type VisitFit} from '../lib/care-planner';
import {trackPublicEvent} from '../lib/public-analytics';
import {clearCarePlannerProgress,loadCarePlannerProgress,saveCarePlannerProgress} from '../lib/care-planner-progress';

const tasks=['Feeding and fresh water','Potty break or dog walk','Play and enrichment','Litter or habitat care','Routine medication','Multiple habitats or detailed preparation'];
const option=<T extends string>(value:T,label:string)=><option value={value}>{label}</option>;

export default function CarePlanner(){
 const[dogs,setDogs]=useState(1),[cats,setCats]=useState(0),[otherPets,setOtherPets]=useState(0),[lifeStage,setLifeStage]=useState<LifeStage>('adult'),[taskList,setTaskList]=useState<string[]>(tasks.slice(0,2)),[alone,setAlone]=useState(8),[bathroom,setBathroom]=useState(8),[feeding,setFeeding]=useState(2),[blocks,setBlocks]=useState<number[]>([0,2]),[overnight,setOvernight]=useState(false),[medication,setMedication]=useState<MedicationNeed>('none'),[behavior,setBehavior]=useState<BehaviorNeed>('none'),[complexity,setComplexity]=useState<RoutineComplexity>('simple'),[separation,setSeparation]=useState<SeparationNeed>('none'),[visitFit,setVisitFit]=useState<VisitFit>('unknown'),[ready,setReady]=useState(false),[cleared,setCleared]=useState(false),[saveEpoch,setSaveEpoch]=useState(0),skipNextSave=useRef(false),started=useRef(false);
 useEffect(()=>{const saved=loadCarePlannerProgress(),frame=requestAnimationFrame(()=>{setDogs(saved.dogs);setCats(saved.cats);setOtherPets(saved.otherPets);setLifeStage(saved.lifeStage);setFeeding(saved.feedingFrequency);setBathroom(saved.bathroomIntervalHours);setAlone(saved.comfortableAloneHours);setBlocks(saved.windowIndexes);setOvernight(saved.overnight);setVisitFit(saved.visitFit);setReady(true)});return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{if(!ready)return;if(skipNextSave.current){skipNextSave.current=false;return}saveCarePlannerProgress({dogs,cats,otherPets,lifeStage,feedingFrequency:feeding,bathroomIntervalHours:bathroom,comfortableAloneHours:alone,windowIndexes:blocks,overnight,visitFit})},[ready,dogs,cats,otherPets,lifeStage,feeding,bathroom,alone,blocks,overnight,visitFit,saveEpoch]);
 const markStarted=()=>{if(!started.current){started.current=true;trackPublicEvent('planner_started')}};
 const result=useMemo(()=>assessCarePlan({dogs,cats,otherPets,lifeStage,feedingFrequency:feeding,bathroomIntervalHours:bathroom,comfortableAloneHours:alone,taskCount:taskList.length,medication,behavior,routineComplexity:complexity,separation,visitFit,windowIndexes:blocks,overnight}),[dogs,cats,otherPets,lifeStage,feeding,bathroom,alone,taskList,medication,behavior,complexity,separation,visitFit,blocks,overnight]);
 const resultAnnouncement=result.suitability==='consultation-required'?'Planning guidance updated. Review with Lauren is required.':`${result.durationMinutes}-minute starting point calculated. Review the planning guidance.`;
 const toggle=(task:string)=>setTaskList(x=>x.includes(task)?x.filter(y=>y!==task):[...x,task]);
 const reset=()=>{skipNextSave.current=true;clearCarePlannerProgress();setDogs(1);setCats(0);setOtherPets(0);setLifeStage('adult');setTaskList(tasks.slice(0,2));setAlone(8);setBathroom(8);setFeeding(2);setBlocks([0,2]);setOvernight(false);setMedication('none');setBehavior('none');setComplexity('simple');setSeparation('none');setVisitFit('unknown');setCleared(true);setSaveEpoch(value=>value+1)};
 const count=dogs+cats+otherPets,household=(dogs&&cats)||(otherPets&&dogs)||(otherPets&&cats)?'Mixed-pet household':dogs?'Dog':cats?'Cat':'Rabbit, bird, fish, or small animal';
 const estimateParams=new URLSearchParams({planner:'1',pets:String(Math.max(1,count)),household,duration:String(result.durationMinutes??30)});if(blocks.length)estimateParams.set('windows',blocks.join(','));if(overnight)estimateParams.set('overnight','1');
 return <div className="planner-grid" onChange={markStarted}><div className="planner-form"><p className="fine-print">Broad household counts, routine intervals, selected windows, and visit fit are saved only for this browser session. Medication, behavior, separation, task details, names, addresses, contact details, and travel dates are never saved here.</p><button type="button" className="text-link" onClick={reset}>Clear saved planner progress and reset</button>{cleared&&<span role="status" className="save-status">Saved planner progress cleared.</span>}
  <fieldset><legend>Household pet counts</legend><label>Dogs<input type="number" min="0" max="8" value={dogs} onChange={e=>setDogs(Math.max(0,Math.min(8,+e.target.value||0)))}/></label><label>Cats<input type="number" min="0" max="8" value={cats} onChange={e=>setCats(Math.max(0,Math.min(8,+e.target.value||0)))}/></label><label>Other accepted pets<input type="number" min="0" max="8" value={otherPets} onChange={e=>setOtherPets(Math.max(0,Math.min(8,+e.target.value||0)))}/></label></fieldset>
  <label>Life stage<select value={lifeStage} onChange={e=>setLifeStage(e.target.value as LifeStage)}>{option('adult','Adult')}{option('puppy','Puppy or very young pet')}{option('senior','Senior')}{option('mixed','Mixed life stages')}</select></label>
  <fieldset><legend>What needs to happen during care?</legend>{tasks.map(task=><label className="check-field" key={task}><input type="checkbox" checked={taskList.includes(task)} onChange={()=>toggle(task)}/><span>{task}</span></label>)}</fieldset>
  <label>Feedings needed per day<input type="number" min="1" max="6" value={feeding} onChange={e=>setFeeding(Math.max(1,Math.min(6,+e.target.value||1)))}/></label>
  <label>Longest normally comfortable alone (hours)<input type="number" min="1" max="24" value={alone} onChange={e=>setAlone(Math.max(1,Math.min(24,+e.target.value||1)))}/></label>
  <label>Longest stated bathroom or walk interval (hours)<input type="number" min="1" max="24" value={bathroom} onChange={e=>setBathroom(Math.max(1,Math.min(24,+e.target.value||1)))}/><small>Enter the household&apos;s established routine, not a veterinary recommendation.</small></label>
  <fieldset><legend>Service windows being considered</legend>{business.windows.map((window,index)=><label className="check-field" key={window.id}><input type="checkbox" checked={blocks.includes(index)} onChange={()=>setBlocks(x=>x.includes(index)?x.filter(y=>y!==index):[...x,index])}/><span>{window.label}</span></label>)}<label className="check-field"><input type="checkbox" checked={overnight} onChange={e=>setOvernight(e.target.checked)}/><span>Overnight care ({business.overnight.label})</span></label><small>Choose daytime windows during an overnight only when you intentionally want midday or other daytime coverage.</small></fieldset>
  <label>Medication timing<select value={medication} onChange={e=>setMedication(e.target.value as MedicationNeed)}>{option('none','None')}{option('routine','Routine, not time-sensitive')}{option('timed','Time-sensitive')}{option('complex','Refusal risk or specialized handling')}{option('procedure','Injection or procedure requiring scope review')}</select></label>
  <label>Behavior or safety consideration<select value={behavior} onChange={e=>setBehavior(e.target.value as BehaviorNeed)}>{option('none','No special handling needs known')}{option('fear','Fearful or slow to warm')}{option('reactive','Reactive or trigger-sensitive')}{option('aggressive','Aggression, bite risk, or handling sensitivity')}{option('escape','Door-dashing or escape risk')}</select><small>Do not enter incident details here. Safety history is reviewed privately.</small></label>
  <label>Routine complexity<select value={complexity} onChange={e=>setComplexity(e.target.value as RoutineComplexity)}>{option('simple','Simple and consistent')}{option('moderate','Several ordered tasks')}{option('complex','Complex timing or task sequence')}{option('unclear','Not sure yet')}</select></label>
  <label>Separation requirements<select value={separation} onChange={e=>setSeparation(e.target.value as SeparationNeed)}>{option('none','None')}{option('feeding','Separate feeding')}{option('handling','Separate handling or care areas')}{option('unclear','Not sure')}</select></label>
  <label>Can the full routine safely fit in one visit?<select value={visitFit} onChange={e=>setVisitFit(e.target.value as VisitFit)}>{option('unknown','Not sure')}{option('30','Yes, within 30 minutes')}{option('60','Yes, within 60 minutes')}{option('90','Yes, within 90 minutes')}{option('neither','No, it may exceed 90 minutes')}</select></label>
 </div><p className="sr-only" role="status">{resultAnnouncement}</p><aside className="planner-result"><p className="eyebrow">Planning guidance</p><h2>{result.suitability==='consultation-required'?'Personalized review required':`${result.durationMinutes}-minute visits may be a useful starting point`}</h2><p>{result.suggestedStartingPoint}</p><dl><div><dt>Longest plausible care gap</dt><dd>{result.longestPlausibleGapHours===null?'Cannot calculate until coverage is selected':`Approximately ${result.longestPlausibleGapHours} hours`}</dd></div><div><dt>Gap comparison</dt><dd>{result.gapWithinEnteredLimits===null?'Not available':result.gapWithinEnteredLimits?'Within the entered household limits':'Longer than at least one entered household limit'}</dd></div></dl><section className="care-gap-visual" aria-labelledby="care-gap-title"><h3 id="care-gap-title">Possible service timing across a day</h3><div className="care-gap-axis" aria-hidden="true"><span>12 AM</span><span>6 AM</span><span>12 PM</span><span>6 PM</span><span>12 AM</span></div><div className="care-gap-track" aria-hidden="true">{overnight&&<><i className="overnight" style={{left:'0%',width:'33.33%'}}/><i className="overnight" style={{left:'75%',width:'25%'}}/></>}{blocks.map(index=>{const window=business.windows[index];return window?<i className="arrival" key={window.id} style={{left:`${window.startHour/24*100}%`,width:`${(window.endHour-window.startHour)/24*100}%`}}/>:null})}</div><ul className="care-gap-key">{overnight&&<li><span className="overnight"/>Approximate overnight coverage: {business.overnight.label}</li>}{blocks.map(index=>business.windows[index]).filter(Boolean).map(window=><li key={window.id}><span className="arrival"/>Possible visit arrival: {window.label}</li>)}</ul><p className="fine-print">Arrival ranges are not continuous coverage or exact appointments. The longest plausible gap uses the least favorable permitted transition between these flexible windows; Lauren confirms the actual schedule.</p></section>{result.reasons.length>0&&<><h3>Why</h3><ul>{result.reasons.map(x=><li key={x}>{x}</li>)}</ul></>}{result.reviewReasons.length>0&&<><h3>Items for consultation</h3><ul>{result.reviewReasons.map(x=><li key={x}>{x}</li>)}</ul></>}<details><summary>Factors and assumptions</summary><h3>Factors</h3><ul>{result.factors.map(x=><li key={x}>{x}</li>)}</ul><h3>Assumptions</h3><ul>{result.assumptions.map(x=><li key={x}>{x}</li>)}</ul></details><h3>Important limits</h3><ul>{result.warnings.map(x=><li key={x}>{x}</li>)}</ul><div className="actions">{count>0&&result.durationMinutes!==null&&<a className="button" href={`/?${estimateParams.toString()}#estimate`} onClick={()=>trackPublicEvent('planner_completed',{duration:result.durationMinutes,status:'success'})}>Price this starting point</a>}<a className="text-link" href="/contact">Ask Lauren</a></div></aside></div>;
}
