'use client';
import {useMemo,useState} from 'react';
import {business} from '../config/business';
import {largestDailyGap} from '../lib/business-rules';

const tasks=['Feeding and fresh water','Potty break or dog walk','Play and enrichment','Litter or habitat care','Medication','Multiple habitats or detailed preparation'];
const households=['Dog','Cat','Dogs and cats','Rabbit, bird, fish, or small animal','Mixed-pet household'] as const;
const behaviors=[['none','No special handling needs known'],['fear','Fearful or slow-to-warm behavior'],['reactivity','Leash reactivity or animal triggers'],['escape','Door-dashing or escape risk'],['bite','Known bite risk or handling sensitivity']] as const;
export default function CarePlanner(){
 const[count,setCount]=useState(1),[types,setTypes]=useState<(typeof households)[number]>('Dog'),[taskList,setTaskList]=useState<string[]>(tasks.slice(0,2)),[alone,setAlone]=useState(8),[blocks,setBlocks]=useState<number[]>([0,2]),[overnight,setOvernight]=useState(false),[meds,setMeds]=useState('none'),[behavior,setBehavior]=useState('none');
 const result=useMemo(()=>{const habitat=/Rabbit|Mixed/.test(types),cats=types==='Cat',workload=count*2+taskList.length+(habitat?2:0)+(cats&&taskList.includes('Litter or habitat care')?1:0)+(meds==='routine'?1:meds==='complex'?4:0);const duration=workload>=9?60:30,gap=largestDailyGap(blocks,overnight),review=meds==='complex'||meds==='injection'||behavior!=='none',adequate=gap!==null&&gap<=alone;return{duration,gap,review,adequate};},[count,types,taskList,alone,blocks,overnight,meds,behavior]);
 const toggle=(task:string)=>setTaskList(x=>x.includes(task)?x.filter(y=>y!==task):[...x,task]);
 const estimateParams=new URLSearchParams({planner:'1',pets:String(count),household:types,duration:String(result.duration)}); if(blocks.length)estimateParams.set('windows',blocks.join(',')); if(overnight)estimateParams.set('overnight','1');
 return <div className="planner-grid"><div className="planner-form">
  <label>How many pets?<input type="number" min="1" max="8" value={count} onChange={e=>setCount(Math.max(1,Math.min(8,+e.target.value||1)))}/></label>
  <label>Household includes<select value={types} onChange={e=>setTypes(e.target.value as typeof types)}>{households.map(x=><option key={x}>{x}</option>)}</select></label>
  <fieldset><legend>What needs to happen during care?</legend>{tasks.map(task=><label className="check-field" key={task}><input type="checkbox" checked={taskList.includes(task)} onChange={()=>toggle(task)}/><span>{task}</span></label>)}</fieldset>
  <label>Longest your pets are normally comfortable alone (hours)<input type="number" min="1" max="24" value={alone} onChange={e=>setAlone(Math.max(1,Math.min(24,+e.target.value||1)))}/></label>
  <fieldset><legend>Windows you are considering each day</legend>{business.windows.map((window,index)=><label className="check-field" key={window.id}><input type="checkbox" checked={blocks.includes(index)} onChange={()=>setBlocks(x=>x.includes(index)?x.filter(y=>y!==index):[...x,index])}/><span>{window.label}</span></label>)}<label className="check-field"><input type="checkbox" checked={overnight} onChange={e=>setOvernight(e.target.checked)}/><span>Overnight care ({business.overnight.label})</span></label>{!blocks.length&&!overnight&&<small>Choose at least one window or overnight care to calculate a gap.</small>}</fieldset>
  <label>Medication needs<select value={meds} onChange={e=>setMeds(e.target.value)}><option value="none">None</option><option value="routine">Oral in food, liquid in food, or routine topical</option><option value="complex">Time-sensitive, refusal risk, or specialized handling</option><option value="injection">Injection or veterinary procedure</option></select></label>
  <label>Behavior or handling consideration<select value={behavior} onChange={e=>setBehavior(e.target.value)}>{behaviors.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><small>Do not enter private incident details here. Lauren reviews safety and handling privately before accepting care.</small></label>
 </div><aside className="planner-result" aria-live="polite"><p className="eyebrow">Planning guidance</p><h2>{result.review?'Additional review needed':`${result.duration}-minute visits may be a useful starting point`}</h2>{result.gap===null?<p>Choose at least one care window to evaluate time between care periods.</p>:<p>{result.adequate?`Using the windows selected, the longest gap between care periods is about ${result.gap} hours, within the ${alone}-hour comfort limit you entered.`:`This schedule could leave about ${result.gap} hours between care periods, longer than the ${alone}-hour comfort limit you entered. Add a window, consider overnight care, or ask Lauren to help plan.`}</p>}{meds==='injection'&&<p><strong>Injections and veterinary procedures are not offered.</strong> Ask your veterinary team about an appropriate care arrangement.</p>}{result.review&&meds!=='injection'&&<p>This is not an automatic rejection. Lauren will privately review the routine, temperament, timing, and handling needs before accepting it.</p>}<p>This is educational planning guidance, not a booking, medical advice, or a guarantee that a schedule is suitable.</p><div className="actions"><a className="button" href={`/#estimate?${estimateParams.toString()}`}>Price this plan</a><a className="text-link" href="/contact">Ask Lauren</a></div></aside></div>;
}
