'use client';
import {useMemo,useState} from 'react';

const tasks=['Feeding and fresh water','Potty break or dog walk','Play and enrichment','Litter or habitat care','Medication'];
export default function CarePlanner(){
 const[count,setCount]=useState(1),[types,setTypes]=useState('Dog'),[taskList,setTaskList]=useState<string[]>(tasks.slice(0,2)),[alone,setAlone]=useState(8),[visits,setVisits]=useState(2),[meds,setMeds]=useState('none'),[behavior,setBehavior]=useState('none');
 const result=useMemo(()=>{const workload=count*2+taskList.length+(meds==='routine'?1:meds==='complex'?4:0);const duration=workload>=8?60:30;const gap=Math.round(24/Math.max(1,visits));const review=meds==='complex'||meds==='injection'||behavior==='review';return{duration,gap,review,adequate:gap<=alone};},[count,taskList,alone,visits,meds,behavior]);
 const toggle=(task:string)=>setTaskList(x=>x.includes(task)?x.filter(y=>y!==task):[...x,task]);
 return <div className="planner-grid"><div className="planner-form">
  <label>How many pets?<input type="number" min="1" max="8" value={count} onChange={e=>setCount(Math.max(1,Math.min(8,+e.target.value||1)))}/></label>
  <label>Household includes<select value={types} onChange={e=>setTypes(e.target.value)}><option>Dog</option><option>Cat</option><option>Dogs and cats</option><option>Rabbit, bird, fish, or small animal</option><option>Mixed-pet household</option></select></label>
  <fieldset><legend>What needs to happen during care?</legend>{tasks.map(task=><label className="check-field" key={task}><input type="checkbox" checked={taskList.includes(task)} onChange={()=>toggle(task)}/><span>{task}</span></label>)}</fieldset>
  <label>Longest your pets are normally comfortable alone (hours)<input type="number" min="1" max="24" value={alone} onChange={e=>setAlone(+e.target.value||1)}/></label>
  <label>Visits you are considering each day<input type="number" min="1" max="4" value={visits} onChange={e=>setVisits(+e.target.value||1)}/></label>
  <label>Medication needs<select value={meds} onChange={e=>setMeds(e.target.value)}><option value="none">None</option><option value="routine">Oral in food or routine topical</option><option value="complex">Time-sensitive, refusal risk, or specialized handling</option><option value="injection">Injection or veterinary procedure</option></select></label>
  <label>Behavior or handling considerations<select value={behavior} onChange={e=>setBehavior(e.target.value)}><option value="none">None known</option><option value="review">Fear, bite risk, escape risk, reactivity, or specialized handling</option></select></label>
 </div><aside className="planner-result" aria-live="polite"><p className="eyebrow">Planning guidance</p><h2>{result.review?'Additional review needed':`${result.duration}-minute visits may be a useful starting point`}</h2><p>{result.adequate?`At ${visits} visit${visits===1?'':'s'} per day, the approximate longest gap is ${result.gap} hours, within the ${alone}-hour comfort limit you entered.`:`This plan could leave an approximate ${result.gap}-hour gap, longer than the ${alone}-hour comfort limit you entered. Consider more visits, an overnight, or ask Lauren to help plan.`}</p>{meds==='injection'&&<p><strong>Injections and veterinary procedures are not offered.</strong> Ask your veterinary team about an appropriate care arrangement.</p>}{result.review&&meds!=='injection'&&<p>This is not an automatic rejection. Lauren will need to review the routine, safety, timing, and handling needs before accepting it.</p>}<p>This is educational planning guidance, not a booking, medical advice, or a guarantee that a schedule is suitable.</p><div className="actions"><a className="button" href="/#estimate">Price this plan</a><a className="text-link" href="/contact">Ask Lauren</a></div></aside></div>;
}
