import {clientKey,rateLimit} from '../../../lib/rate-limit.ts';
import {addressFeaturesAvailable,classifyTypicalTravel,isAddressValidationResponse,parseAddressValidation} from '../../../lib/address.ts';
import {fetchWithTimeout,readJsonObject} from '../../../lib/server-security.ts';
import {providerFailureForException,providerFailureForStatus} from '../../../lib/providers/errors.ts';
import {createRequestId,jsonWithRequestId,logDiagnostic,logProviderFailure} from '../../../lib/observability.ts';
export async function POST(request:Request){
 const requestId=createRequestId(),json=(body:unknown,init:ResponseInit={})=>jsonWithRequestId(body,requestId,{...init,headers:new Headers({'Cache-Control':'no-store',...Object.fromEntries(new Headers(init.headers))})});
 const limit=rateLimit(`address-check:${clientKey(request)}`,12,5*60_000);if(!limit.allowed){logDiagnostic('WARN','security.rate_limited',{operation:'address-check',requestId,category:'RATE_LIMIT',result:'rejected'});return json({error:'Please wait and try again.'},{status:429,headers:{'Retry-After':String(limit.retryAfter)}})}
 const key=process.env.GOOGLE_MAPS_SERVER_KEY,origin=process.env.PRIVATE_SERVICE_ORIGIN;if(!addressFeaturesAvailable(key,origin)){logDiagnostic('DEBUG','configuration.optional_disabled',{operation:'address-check',provider:'google-maps-platform',requestId,category:'CONFIGURATION',result:'unavailable'});return json({available:false},{status:503})}
 const parsed=await readJsonObject(request,1024,['address']);if(!parsed.ok)return json({error:parsed.error},{status:parsed.status});const address=typeof parsed.value.address==='string'?parsed.value.address.trim():'';if(address.length<6||address.length>180)return json({error:'Enter a complete street address.'},{status:400});
 const validationStarted=Date.now();
 try{const validation=await fetchWithTimeout('https://addressvalidation.googleapis.com/v1:validateAddress',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key!},body:JSON.stringify({address:{regionCode:'US',addressLines:[address]}})},5000);if(!validation.ok){logProviderFailure('google-maps-platform','address-validation',requestId,providerFailureForStatus(validation.status),Date.now()-validationStarted);return json({available:false},{status:503})}const validationPayload:unknown=await validation.json();if(!isAddressValidationResponse(validationPayload)){logDiagnostic('WARN','provider.response_rejected',{provider:'google-maps-platform',operation:'address-validation',requestId,durationMs:Date.now()-validationStarted,category:'VALIDATION_REJECTED',result:'malformed'});return json({available:false},{status:503})}const normalized=parseAddressValidation(validationPayload);if(!normalized)return json({error:'We could not confirm that address. Contact Lauren for a travel review.'},{status:422});logDiagnostic('DEBUG','provider.call_completed',{provider:'google-maps-platform',operation:'address-validation',requestId,durationMs:Date.now()-validationStarted,result:'accepted'});let travelTier:ReturnType<typeof classifyTypicalTravel>;const routeStarted=Date.now();try{const route=await fetchWithTimeout('https://routes.googleapis.com/directions/v2:computeRoutes',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key!,'X-Goog-FieldMask':'routes.duration'},body:JSON.stringify({origin:{address:origin},destination:{address:normalized.normalizedDestination||address},travelMode:'DRIVE',routingPreference:'TRAFFIC_UNAWARE'})},5000);if(route.ok){const data=await route.json() as {routes?:{duration?:string}[]},seconds=Number((data.routes?.[0]?.duration||'').replace('s',''));travelTier=classifyTypicalTravel(seconds);logDiagnostic('DEBUG','provider.call_completed',{provider:'google-maps-platform',operation:'route-duration',requestId,durationMs:Date.now()-routeStarted,result:travelTier?'accepted':'no_tier'})}else logProviderFailure('google-maps-platform','route-duration',requestId,providerFailureForStatus(route.status),Date.now()-routeStarted)}catch(error){logProviderFailure('google-maps-platform','route-duration',requestId,providerFailureForException(error),Date.now()-routeStarted)}return json({available:true,zip:normalized.zip,city:normalized.city,travelTier,travelContext:travelTier?`${travelTier.name} based on typical one-way travel`:'Personalized travel review required'})}catch(error){logProviderFailure('google-maps-platform','address-validation',requestId,providerFailureForException(error),Date.now()-validationStarted);return json({available:false},{status:503})}
}
