import {clientKey,rateLimit} from '../../../lib/rate-limit.ts';
import {addressFeaturesAvailable,parseAddressValidation,routeContext} from '../../../lib/address.ts';
import {zoneForDriveSeconds,zoneForZip} from '../../../lib/business-rules.ts';
import {fetchWithTimeout,readJsonObject} from '../../../lib/server-security.ts';
export async function POST(request:Request){
 const limit=rateLimit(`address-check:${clientKey(request)}`,12,5*60_000);if(!limit.allowed)return Response.json({error:'Please wait and try again.'},{status:429,headers:{'Cache-Control':'no-store','Retry-After':String(limit.retryAfter)}});
 const key=process.env.GOOGLE_MAPS_SERVER_KEY,origin=process.env.PRIVATE_SERVICE_ORIGIN;if(!addressFeaturesAvailable(key,origin))return Response.json({available:false},{status:503,headers:{'Cache-Control':'no-store'}});
 const parsed=await readJsonObject(request,1024,['address']);if(!parsed.ok)return Response.json({error:parsed.error},{status:parsed.status,headers:{'Cache-Control':'no-store'}});const address=typeof parsed.value.address==='string'?parsed.value.address.trim():'';if(address.length<6||address.length>180)return Response.json({error:'Enter a complete street address.'},{status:400,headers:{'Cache-Control':'no-store'}});
 try{const validation=await fetchWithTimeout(`https://addressvalidation.googleapis.com/v1:validateAddress?key=${encodeURIComponent(key!)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:{regionCode:'US',addressLines:[address]}})},5000);if(!validation.ok)throw new Error();const normalized=parseAddressValidation(await validation.json());if(!normalized)return Response.json({error:'We could not confirm that address. Try the ZIP checker instead.'},{status:422,headers:{'Cache-Control':'no-store'}});let travelContext:string|undefined,zone:ReturnType<typeof zoneForZip>|ReturnType<typeof zoneForDriveSeconds> = zoneForZip(normalized.zip);try{const route=await fetchWithTimeout('https://routes.googleapis.com/directions/v2:computeRoutes',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key!,'X-Goog-FieldMask':'routes.duration,routes.distanceMeters'},body:JSON.stringify({origin:{address:origin},destination:{address:normalized.normalizedDestination||address},travelMode:'DRIVE'})},5000);if(route.ok){const data=await route.json() as {routes?:{duration?:string;distanceMeters?:number}[]},first=data.routes?.[0],seconds=Number((first?.duration||'').replace('s',''));if(first){travelContext=routeContext(seconds,first.distanceMeters||0);const driveZone=zoneForDriveSeconds(seconds);if(driveZone.state!=='incomplete')zone=driveZone}}}catch{}return Response.json({available:true,zip:normalized.zip,city:normalized.city,zone,travelContext},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({available:false},{status:503,headers:{'Cache-Control':'no-store'}})}
}
