import {clientKey,rateLimit} from '../../../lib/rate-limit.ts';
import {parseAutocomplete} from '../../../lib/address.ts';
import {fetchWithTimeout,readJsonObject} from '../../../lib/server-security.ts';
import {providerFailureForException,providerFailureForStatus} from '../../../lib/providers/errors.ts';
import {createRequestId,jsonWithRequestId,logDiagnostic,logProviderFailure} from '../../../lib/observability.ts';
export async function POST(request:Request){
 const requestId=createRequestId(),json=(body:unknown,init:ResponseInit={})=>jsonWithRequestId(body,requestId,{...init,headers:new Headers({'Cache-Control':'no-store',...Object.fromEntries(new Headers(init.headers))})});
 const limit=rateLimit(`address-suggest:${clientKey(request)}`,25,5*60_000);if(!limit.allowed){logDiagnostic('WARN','security.rate_limited',{operation:'address-suggestions',requestId,category:'RATE_LIMIT',result:'rejected'});return json({error:'Please wait and try again.'},{status:429,headers:{'Retry-After':String(limit.retryAfter)}})}
 const key=process.env.GOOGLE_MAPS_SERVER_KEY;if(!key){logDiagnostic('DEBUG','configuration.optional_disabled',{operation:'address-suggestions',provider:'google-maps-platform',requestId,category:'CONFIGURATION',result:'unavailable'});return json({available:false,suggestions:[]},{status:503})}
 const parsed=await readJsonObject(request,1024,['input']);if(!parsed.ok)return json({error:parsed.error},{status:parsed.status});const input=typeof parsed.value.input==='string'?parsed.value.input.trim():'';if(input.length>180)return json({error:'Address search is too long.'},{status:400});if(input.length<4)return json({available:true,suggestions:[]});
 const started=Date.now();try{const response=await fetchWithTimeout('https://places.googleapis.com/v1/places:autocomplete',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':'suggestions.placePrediction.placeId,suggestions.placePrediction.text.text'},body:JSON.stringify({input,includedRegionCodes:['us'],locationBias:{circle:{center:{latitude:38.5816,longitude:-121.4944},radius:50000}}})},5000);if(!response.ok){logProviderFailure('google-maps-platform','address-suggestions',requestId,providerFailureForStatus(response.status),Date.now()-started);return json({available:false,suggestions:[]},{status:503})}const suggestions=parseAutocomplete(await response.json());logDiagnostic('DEBUG','provider.call_completed',{provider:'google-maps-platform',operation:'address-suggestions',requestId,durationMs:Date.now()-started,result:'accepted'});return json({available:true,suggestions})}catch(error){logProviderFailure('google-maps-platform','address-suggestions',requestId,providerFailureForException(error),Date.now()-started);return json({available:false,suggestions:[]},{status:503})}
}
