import {dateRange,MAX_ICS_BYTES,publicAvailability,validIsoDate} from '../../lib/availability.ts';
import {clientKey,rateLimit} from '../../lib/rate-limit.ts';
import {fetchWithTimeout,readJsonObject,safeCalendarUrl} from '../../lib/server-security.ts';
import {providerFailureForException,providerFailureForStatus} from '../../lib/providers/errors.ts';
import {createRequestId,jsonWithRequestId,logDiagnostic,logProviderFailure} from '../../lib/observability.ts';
const disclaimer='Calendar space is not operational capacity. Every request requires route, travel, care-time, documentation, buffer, and existing-commitment review before availability is confirmed.';
export async function POST(request:Request){
 const requestId=createRequestId(),json=(body:unknown,init:ResponseInit={})=>jsonWithRequestId(body,requestId,{...init,headers:new Headers({'Cache-Control':'no-store',...Object.fromEntries(new Headers(init.headers))})});
 const limit=rateLimit(`availability:${clientKey(request)}`,30,5*60_000);if(!limit.allowed){logDiagnostic('WARN','security.rate_limited',{operation:'availability',requestId,category:'RATE_LIMIT',result:'rejected'});return json({error:'Too many checks. Please wait and try again.'},{status:429,headers:{'Retry-After':String(limit.retryAfter)}})}
 const parsed=await readJsonObject(request,256,['start','end']);if(!parsed.ok)return json({error:parsed.error},{status:parsed.status});const start=typeof parsed.value.start==='string'?parsed.value.start:'',end=typeof parsed.value.end==='string'?parsed.value.end:'';if(!validIsoDate(start)||!validIsoDate(end)||end<start)return json({error:'Choose a valid date range.'},{status:400});
 const days=dateRange(start,end);if(days.length<1||days.length>31)return json({error:'Choose a range of 31 days or fewer.'},{status:400});
 const fallback=()=>json({state:'Request for Review',days:days.map(date=>({date,status:'Request for Review'})),lastUpdated:new Date().toISOString(),source:'fallback',disclaimer});
 const calendarUrl=safeCalendarUrl(process.env.PRIVATE_CALENDAR_ICS_URL||'');if(!calendarUrl){logDiagnostic('DEBUG','configuration.optional_disabled',{operation:'availability',provider:'private-calendar-host',requestId,category:'CONFIGURATION',result:'fallback'});return fallback()}
 const started=Date.now();
 try{const response=await fetchWithTimeout(calendarUrl,{headers:{Accept:'text/calendar'},cache:'no-store'},7000);const declared=Number(response.headers.get('content-length'));if(!response.ok){logProviderFailure('private-calendar-host','availability-read',requestId,providerFailureForStatus(response.status),Date.now()-started);return fallback()}if(Number.isFinite(declared)&&declared>MAX_ICS_BYTES){logDiagnostic('WARN','provider.response_rejected',{provider:'private-calendar-host',operation:'availability-read',requestId,durationMs:Date.now()-started,category:'VALIDATION_REJECTED',result:'oversized'});return fallback()}const result=publicAvailability(await response.text(),days);logDiagnostic('DEBUG','provider.call_completed',{provider:'private-calendar-host',operation:'availability-read',requestId,durationMs:Date.now()-started,result:'accepted'});return json({...result,lastUpdated:new Date().toISOString(),source:'calendar',disclaimer})}catch(error){logProviderFailure('private-calendar-host','availability-read',requestId,providerFailureForException(error),Date.now()-started);return fallback()}
}
