import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {business} from '../app/config/business.ts';
import {daysBetween,holidayForDate,publicHolidays,shortNoticeKind} from '../app/lib/business-rules.ts';
import {contactKeys} from '../app/lib/contact.ts';
import {assertTimeZoneSupported,resolveWallClock} from '../app/lib/time.ts';

const root=fileURLToPath(new URL('../',import.meta.url));
const source=relative=>readFileSync(path.join(root,relative),'utf8');

assert.equal(business.timezone,'America/Los_Angeles');
assert.equal(assertTimeZoneSupported(),true);
assert.deepEqual(daysBetween('2026-03-07','2026-03-09'),['2026-03-07','2026-03-08','2026-03-09']);
assert.equal(resolveWallClock('2026-03-08',2,30).kind,'nonexistent');
assert.equal(resolveWallClock('2026-11-01',1,30).kind,'ambiguous');
assert.equal(shortNoticeKind('2026-09-06',9,new Date('2026-09-06T06:50:00Z')),'short-notice');
assert.equal(contactKeys.includes('startedAt'),false);
assert.equal(source('app/contact/ContactTools.tsx').includes('startedAt'),false);
assert.equal(source('app/lib/business-rules.ts').includes('new Date(`${serviceDate}'),false);
assert.equal(source('app/sitemap.ts').includes('lastModified:new Date()'),false);
assert.equal(business.policyStatus.holidayCalendar,'CURRENT / APPROVED');
assert.equal(publicHolidays(2026).length,8);
assert.equal(publicHolidays(2027).length,9);
assert.equal(publicHolidays(2028).length,9);
assert.equal(publicHolidays(2029).length,1);
assert.equal(publicHolidays(2030).length,0);
assert.equal(holidayForDate('2026-01-16')?.id,'mlk-2026');
assert.equal(holidayForDate('2026-01-19')?.id,'mlk-2026');
assert.equal(holidayForDate('2026-01-20'),undefined);
assert.equal(holidayForDate('2026-12-25')?.id,'winter-2026');
assert.equal(holidayForDate('2027-01-03')?.id,'winter-2026');
assert.equal(holidayForDate('2027-01-04'),undefined);
assert.equal(holidayForDate('2027-12-24')?.id,'winter-2027');
assert.equal(holidayForDate('2028-01-03')?.id,'winter-2027');
assert.equal(holidayForDate('2028-01-04'),undefined);
assert.equal(holidayForDate('2028-12-24')?.id,'winter-2028');
assert.equal(holidayForDate('2029-01-03')?.id,'winter-2028');
assert.equal(holidayForDate('2029-01-04'),undefined);

console.log('Time safety check passed: Pacific business rules, date-only arithmetic, client/server clock authority, deterministic sitemap metadata, and approved 2026–2028 holiday boundaries are intact.');
