'use client';
import {useMemo,useRef,useState} from 'react';
import {trackPublicEvent} from '../lib/public-analytics';
import {business} from '../config/business';

const entries=[
['Getting started','Do new clients need a meet-and-greet?','A complimentary initial meet-and-greet is generally expected unless Lauren personally approves a rare exception. Completing it does not automatically approve a booking.'],
['Pricing','What if I need care at short notice?',`A daytime request made less than 24 hours before service may have a $${business.pricing.shortNoticeVisit} per-visit charge. A same-day daytime request may instead have a $${business.pricing.sameDayVisit} charge. An overnight request made less than 48 hours ahead may have a $${business.pricing.shortNoticeOvernight} per-night charge. These discretionary charges do not guarantee availability.`],
['Policies','What is the cancellation policy?','Daytime service: 24 hours or more has no cancellation fee; under 24 hours may be charged 50%; after travel to the location or service begins may be charged 100%. Overnight or vacation care under seven nights uses 72-hour and 24-hour thresholds. For cancellation purposes, 3–8 hour Continuous Care is daytime; 24-Hour Continuous Care is Overnight/multi-day capacity, and seven or more consecutive 24-hour periods use the Extended Booking rules. Approved holiday periods use the corresponding longer daytime or Overnight framework. The signed policy and booking details control, and compassionate exceptions may be considered.'],
['Pricing','Which dates have holiday charges?',`Exact calendars are approved for 2026, 2027, and 2028, including each Christmas/New Year period through January 3 of the following year. The Holiday planning page lists every approved period. The charge is $${business.pricing.holidayVisit} per qualifying daytime arrival and $${business.pricing.holidayOvernight} per qualifying Overnight or 24-hour period. Dates after January 3, 2029 remain inactive until separately approved.`],
['Services','What does a standard overnight include?',`Standard Overnight Care is approximately ${business.overnight.label}. It bundles the core overnight stay but is not continuous presence or a 14-hour hourly service. Reasonable departures may occur when compatible with every pet’s disclosed maximum safe and comfortable alone time, feeding, elimination, medication, nighttime needs, behavior, and the confirmed care plan. Daytime care is separate; a 30-minute midday service is $${business.pricing.overnightMidday30.dog} for a dog household or $${business.pricing.overnightMidday30.cat} for a cat/small-animal household.`],
['Services','What is Continuous Care?',`Continuous Care is a dedicated consecutive block at your residence. The sitter generally remains for the block and leaves only for an emergency or a departure specifically discussed and approved. Rates are household-based and bundle routine care: 3 hours $90, 4 hours $120, 5 hours $145, 6 hours $165, 7 hours $185, and an 8-hour Extended Day $200. It is not boarding, daycare, veterinary monitoring, or a second-by-second guarantee.`],
['Services','Do you offer true 24-hour care?',`Limited 24-Hour Continuous Care may be available by request and starts at $${business.pricing.continuous24Starting} per 24-hour period. It is household-based, includes ordinary routine care and resting time, and is not $30 multiplied by 24. Capacity, safety, timing, travel, and scope require individualized review; a request or payment does not guarantee acceptance.`],
['Services','Should I choose scheduled visits or Continuous Care?','Scheduled visits are usually the more affordable fit when every pet can safely and comfortably remain alone between care periods. Continuous Care is considered when the disclosed routine and maximum alone-time limits require a dedicated consecutive block; it is a care-fit decision, not an automatic upsell.'],
['Scheduling','Are visit times exact?','Choose preferred windows of 9 AM–12 PM, 12–3 PM, 3–6 PM, or 6–9 PM. Exact arrival times are confirmed based on the approved routine, medication timing, travel, safety, and schedule.'],
['Pricing','Does an online estimate guarantee my price or dates?',"No. It is a planning tool. Final pricing, timing, care fit, and availability require Lauren’s review and approval."],
['Health','Can you give medication?','Medication requests require written instructions and individual scope, timing, handling, safety, and suitability review. The site does not promise a particular administration method while the governing training and service-scope reference is awaiting approval.'],
['Small animals','How are small animals priced?',`Routine 30-minute care starts at $${business.pricing.drop30.other} and 60-minute care at $${business.pricing.drop60.other}. Fish are generally priced per typical tank. Each additional rabbit, bird, tank, cat, or small animal starts at $${business.pricing.additionalOther} per visit. Complex routines may need a longer or custom plan.`],
['Pets','Do you care for puppies or senior pets?','Puppies, senior pets, anxious pets, and pets with medical or disability-related needs are considered individually. There is no automatic surcharge for those traits; pricing follows the actual service needed. Intensive needs may require a longer or custom plan, personalized review, or referral when they fall outside safe service scope.'],
['Safety','What are the walking safety rules?','Dogs need secure, properly fitting equipment and remain leashed. Outdoor activity may be shortened, changed, or stopped when temperature, pavement, smoke, storms, air quality, or other conditions make the planned activity unsafe.'],
['Safety','How are emergencies handled?',"Lauren follows the current client profile and signed agreement, attempts to reach the client or authorized contact, and may seek veterinary help when care should not reasonably be delayed."],
['Safety','Can pet-care technology replace in-person visits?','Automatic feeders, water fountains, self-cleaning litter boxes, approved cameras, smart doors, and other routine household technology may support an approved care plan, but they do not automatically replace appropriate in-person welfare checks. Keep a practical backup plan in secure Precise Petcare records for device, power, or network failure. Cuddle Crew does not connect to or remotely monitor client devices, and this is not veterinary monitoring.'],
['Privacy','How is home access handled?','Keys, codes, and household instructions are confidential and used only for approved care. Put them in the secure client portal and review backup access at the meet-and-greet.'],
['Services','Which requests need extra review?','Continuous Care, 24-Hour Continuous Care, transportation, medication or procedures, exact-time care, unusual species, complex handling, and large or intensive households require personalized review. Continuous Care is limited-capacity, not categorically unavailable. A higher price never overrides safety, legal, insurance, or service-scope limits.'],
['Privacy','What about pet photos?','All client pet photos shown on this site are shared with written permission from the client or pet owner. That permission does not extend to client identities, private household details, medical information, testimonials, addresses, or other client records. Any future client media still requires the applicable permission and approved consent record.']
] as const;

export default function FAQSearch(){
 const[q,setQ]=useState(''),[cat,setCat]=useState('All'),tracked=useRef(false);
 const cats=['All',...new Set(entries.map(x=>x[0]))];
 const shown=useMemo(()=>entries.filter(([c,t,a])=>(cat==='All'||c===cat)&&`${t} ${a}`.toLowerCase().includes(q.toLowerCase())),[q,cat]);
 const search=(value:string)=>{setQ(value);if(value.trim().length>=2&&!tracked.current){tracked.current=true;trackPublicEvent('faq_searched')}};
 return <><div className="faq-tools"><label>Search questions<input type="search" value={q} onChange={e=>search(e.target.value)} placeholder="Try medication, cancellation, puppy…"/></label><label>Category<select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select></label></div><p role="status">{shown.length} question{shown.length===1?'':'s'} found</p><div className="accordion-list">{shown.map(([c,t,a])=><details key={t}><summary><span>{t}</span><small>{c}</small></summary><p>{a}</p></details>)}</div>{!shown.length&&<div className="content-card"><h2>No exact match</h2><p><a href="/contact">Ask Lauren directly</a>, or try a broader search term.</p></div>}</>;
}
