import SiteHeader from '../SiteHeader';

export default function FAQ() {
  return <main className="shell">
    <SiteHeader/>
    <section className="subhero"><p className="eyebrow">Policies & FAQ</p><h1>Kind, clear expectations.</h1><p className="lede">A little planning helps every pet receive calm, consistent care.</p></section>
    <section className="content-card"><h2>Do new clients need a meet-and-greet?</h2><p>Yes. A complimentary meet-and-greet is required for every new household before the first service. Registration and booking requests are not automatic confirmations. Your dates are reserved only after Lauren reviews the location, care needs, temperament, health requirements, and schedule—and manually approves the request.</p></section>
    <section className="content-card"><h2>What if I need care at the last minute?</h2><p>Requests made under 24 hours depend on availability and may include a <strong>$10 surcharge per daytime visit</strong> or a <strong>$25 surcharge per overnight</strong>.</p></section>
    <section className="content-card"><h2>What is the cancellation policy?</h2><ul><li><strong>48+ hours ahead:</strong> full refund</li><li><strong>Under 48 hours:</strong> 50% charge</li><li><strong>Same day:</strong> charged in full</li></ul></section>
    <section className="content-card"><h2>Which dates are holidays?</h2><p>New Year’s Day, Easter, Mother’s Day, Independence Day, Thanksgiving, Christmas Eve, Christmas Day, and New Year’s Eve. Holiday daytime visits include an additional $15 per visit, and holiday overnight care includes an additional $30 per day.</p></section>
    <section className="content-card"><h2>What does an overnight include?</h2><p>Overnight care covers the approximately 6 PM–8 AM stay. It does not include a midday visit. A same-day 30-minute drop-in can be added at a discounted bundled rate for both single-night and multi-night bookings; the listed one-dog overnight bundle is $105. Other household combinations are confirmed individually.</p></section>
    <section className="content-card"><h2>Can you give medication?</h2><p>With clear, current written instructions, Lauren can provide pills crushed into food, liquid medication mixed into food, and routine topical medication such as a client-provided antiseptic. Injections, veterinary procedures, and medication administration that requires specialized training or creates a bite risk are not offered. Every medication request must be reviewed and accepted in advance.</p></section>
    <section className="content-card"><h2>Do you care for puppies, senior pets, or pets with special needs?</h2><p>Senior pets are welcome. Dogs under one year old are considered individually because many puppies need more frequent daytime attention than the schedule can reliably accommodate. All care requests are reviewed based on the pet’s routine, temperament, health needs, handling requirements, household circumstances, and Lauren’s ability to provide safe, comfortable care.</p></section>
    <section className="content-card"><h2>What are the dog-walking safety rules?</h2><p>Dogs must have a secure, properly fitting collar or harness and remain leashed outside a securely enclosed private area. Off-leash walks and dog-park visits are not offered. Walks are not provided when the outdoor temperature is above 85°F or when pavement, smoke, storms, or other conditions are unsafe. The visit may instead include a brief potty break and appropriate indoor enrichment.</p></section>
    <section className="content-card"><h2>How are emergencies handled?</h2><p>Please provide current veterinary and emergency-contact information. Lauren will make reasonable efforts to contact you or your authorized contact and follow the emergency instructions in your client profile. When care should not be delayed, she may contact a veterinarian and transport or arrange transportation to an appropriate veterinary facility. Veterinary, treatment, and transportation costs remain the client’s responsibility unless otherwise required by law.</p></section>
    <section className="content-card"><h2>How is home access handled?</h2><p>Entry instructions, keys, codes, and household details are treated as confidential and used only to provide scheduled care. Access arrangements are reviewed during the meet-and-greet.</p></section>
    <section className="content-card"><h2>Are small household tasks included?</h2><p>Minor tasks may be included when requested and agreed in advance, such as bringing in mail or packages, adjusting lights or window coverings, moving trash or recycling bins, watering plants, and maintaining reasonable thermostat settings. Pet care does not include professional housekeeping, landscaping, maintenance, pool care, security, or property management.</p></section>
    <section className="content-card"><h2>Which services are not offered?</h2><p>Cuddle Crew does not provide boarding in Lauren’s home, continuous 24-hour care, grooming, training, veterinary procedures, injections, off-leash walks, or dog-park visits. Transportation is not a general pet-taxi service, but veterinary transportation may be agreed in advance or used when reasonably necessary during an emergency.</p></section>
    <section className="content-card"><h2>What about privacy and pet photos?</h2><p>Client and household information is used only to coordinate and provide requested services. Pet photos are shared publicly only with permission and are not presented as reviews or endorsements.</p></section>
    <section className="content-card"><h2>How do I get started?</h2><p>New clients can <a href="https://cuddlecrewpetcare.petssl.com/account">register and request availability online</a>. Existing clients can <a href="https://cuddlecrewpetcare.petssl.com/login">log in here</a>. Questions? Email <a href="mailto:lauren@cuddlecrewpetcare.com">lauren@cuddlecrewpetcare.com</a> or call <a href="tel:+19162523550">916-252-3550</a>.</p></section>
    <p><a className="text-link" href="/">← Return home</a></p>
  </main>;
}
